{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-26.3-fabric",
    "version": "2.13.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-26.3-fabric-2.13.0.1.jar",
          "url": "homeostatic-26.3-fabric-2.13.0.1.jar",
          "size": 3006024,
          "sha512": "54705145059e4595bf206727b9b4df62fb25df2c93c76bd66ea94f63d525a55633c45655d7f02af571879c07aafc64a3299683977a2614be6cc7a9d56b5c89c7",
          "sha256": "ab0bcf1c4840cf6a1bae0d8d2efbc6b16b0e00ebf791a034fcaff40e89092613",
          "sha1": "b420e2d26779382214c6175befb424472e381c1a",
          "md5": "f9227f4ca26c99696565efc8a74a6f79"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-26.3-fabric",
          "version": "2.13.0.1"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.13.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.3-fabric",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.3-fabric",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-26.3-fabric",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-26.3-fabric",
          "version": {
            "requires": "1.2.0.3"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-26.3-fabric-2.13.0.1.jar",
          "url": "homeostatic-26.3-fabric-2.13.0.1.jar",
          "size": 3006024,
          "sha512": "54705145059e4595bf206727b9b4df62fb25df2c93c76bd66ea94f63d525a55633c45655d7f02af571879c07aafc64a3299683977a2614be6cc7a9d56b5c89c7",
          "sha256": "ab0bcf1c4840cf6a1bae0d8d2efbc6b16b0e00ebf791a034fcaff40e89092613",
          "sha1": "b420e2d26779382214c6175befb424472e381c1a",
          "md5": "f9227f4ca26c99696565efc8a74a6f79"
        }
      ]
    }
  ]
}
