{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.1-fabric",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.3.jar",
          "url": "handbook-26.1.1-fabric-1.2.3.jar",
          "size": 652586,
          "sha512": "ea4333ca53504b5785d8cd9cd0d61324158e99c61f78e68764963266a71cc6908627de4965a5b226ec425e2e11ea55e71764745a9e3b84d5e4b977301751ce93",
          "sha256": "d5cc14f1e6a3ac2d29d48c5cc517b957ea3d2a18f846d66c7fb99f42ac31b93e",
          "sha1": "9567a8df7fe56c995bd520d17d5ecabe0e8eb0fb",
          "md5": "a722ded9195ade88a26e328bb03dc941"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.3"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.2+26.1.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "18.0.0-alpha.8"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.3.jar",
          "url": "handbook-26.1.1-fabric-1.2.3.jar",
          "size": 652586,
          "sha512": "ea4333ca53504b5785d8cd9cd0d61324158e99c61f78e68764963266a71cc6908627de4965a5b226ec425e2e11ea55e71764745a9e3b84d5e4b977301751ce93",
          "sha256": "d5cc14f1e6a3ac2d29d48c5cc517b957ea3d2a18f846d66c7fb99f42ac31b93e",
          "sha1": "9567a8df7fe56c995bd520d17d5ecabe0e8eb0fb",
          "md5": "a722ded9195ade88a26e328bb03dc941"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.3"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.3-sources.jar",
          "url": "handbook-26.1.1-fabric-1.2.3-sources.jar",
          "size": 435676,
          "sha512": "b7781cc7660405beae340ac9ffec9d48b5bbede733dab2853276f0dd487d7a639abfe261d8f4e3541a0b554f3814f91ed53e756735bd85c474f59566f1d98223",
          "sha256": "e30570c4b520314cb54bf788be8ac8d53250bf30d484a4872a8c09b805b8bb70",
          "sha1": "31efab1833f43ce11367693cc8ea253a8aa333f3",
          "md5": "4eba2082c9e147c654fa817c670c9533"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.3"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.3"
        }
      ]
    }
  ]
}
