{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-26.1.2-common",
    "version": "2.12.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-26.1.2-common-2.12.0.0.jar",
          "url": "homeostatic-26.1.2-common-2.12.0.0.jar",
          "size": 1574166,
          "sha512": "7334bc659836cf9168cd11c51b8fd9834dbe5eeec17983d5531f0c9931d17533a80b892daaee55cffc99eb855b76748f0e2c8240b377dd5f2fc7f8179b7be746",
          "sha256": "2fb6f896ce864d148ff07d6e5a3624255825d7a68ec3e34a3d91d41eb26e9f49",
          "sha1": "b5e73c7781abc0c476f490e896044135ed9e6677",
          "md5": "f5538a7e9e19e92b6cb1710847eaf1cd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.12.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-26.1.2-common",
          "version": "2.12.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.2-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.1.2-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-26.1.2-common",
          "version": {
            "requires": "1.1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-26.1.2-common-2.12.0.0.jar",
          "url": "homeostatic-26.1.2-common-2.12.0.0.jar",
          "size": 1574166,
          "sha512": "7334bc659836cf9168cd11c51b8fd9834dbe5eeec17983d5531f0c9931d17533a80b892daaee55cffc99eb855b76748f0e2c8240b377dd5f2fc7f8179b7be746",
          "sha256": "2fb6f896ce864d148ff07d6e5a3624255825d7a68ec3e34a3d91d41eb26e9f49",
          "sha1": "b5e73c7781abc0c476f490e896044135ed9e6677",
          "md5": "f5538a7e9e19e92b6cb1710847eaf1cd"
        }
      ]
    }
  ]
}
