{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-26.1.2-fabric",
    "version": "2.11.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-26.1.2-fabric-2.11.0.9.jar",
          "url": "homeostatic-26.1.2-fabric-2.11.0.9.jar",
          "size": 2974713,
          "sha512": "e1c436b52550de52822a4e00ce4571182815f71be40dcc9d9e3f6bc8729dad4025ad98feda82e31783ebc6cbef6212909dff1490dc948476409e0bb839573cf0",
          "sha256": "3273356a0b8b07e320ee48404803e9f29af4bc2f94bbc34337999c2e5f0ad4f5",
          "sha1": "477cbe922ff5ddb8674320dcc528d54f5c9761ee",
          "md5": "0989f2bceba1e256b596697de9e46bc5"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.9"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-26.1.2-fabric",
          "version": "2.11.0.9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.146.1+26.1.2"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.1.2-fabric",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.2-fabric",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-26.1.2-fabric",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-26.1.2-fabric",
          "version": {
            "requires": "1.1.0.13"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "8.0.0-alpha.5+26.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "8.0.0-alpha.5+26.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-26.1.2-fabric-2.11.0.9.jar",
          "url": "homeostatic-26.1.2-fabric-2.11.0.9.jar",
          "size": 2974713,
          "sha512": "e1c436b52550de52822a4e00ce4571182815f71be40dcc9d9e3f6bc8729dad4025ad98feda82e31783ebc6cbef6212909dff1490dc948476409e0bb839573cf0",
          "sha256": "3273356a0b8b07e320ee48404803e9f29af4bc2f94bbc34337999c2e5f0ad4f5",
          "sha1": "477cbe922ff5ddb8674320dcc528d54f5c9761ee",
          "md5": "0989f2bceba1e256b596697de9e46bc5"
        }
      ]
    }
  ]
}
