{
  "formatVersion": "1.1",
  "component": {
    "group": "technololgy.roughness.whitenoise",
    "module": "whitenoise-common",
    "version": "1.21.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.4.jar",
          "url": "whitenoise-common-1.21.1.4.jar",
          "size": 132495,
          "sha512": "0141aabb6efb598e61e99e6b164edb5e04999100767c27284cbb4cd2ea95e8717f045a7e4df8033a7e5dbaf76968eecdfa6d820ae83976f2593954c17312b390",
          "sha256": "342e7543960c6834f8e10f25582406697b9507c6fecc49eed907fcf26f78b722",
          "sha1": "543782e157c5008eac7c05747e800c3273d1c466",
          "md5": "c9fe22d7a78ee035bbd1740cbe39fa03"
        }
      ],
      "capabilities": [
        {
          "group": "technololgy.roughness.whitenoise",
          "name": "whitenoise-Common",
          "version": "1.21.1.4"
        },
        {
          "group": "technololgy.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-common-1.21.1.4.jar",
          "url": "whitenoise-common-1.21.1.4.jar",
          "size": 132495,
          "sha512": "0141aabb6efb598e61e99e6b164edb5e04999100767c27284cbb4cd2ea95e8717f045a7e4df8033a7e5dbaf76968eecdfa6d820ae83976f2593954c17312b390",
          "sha256": "342e7543960c6834f8e10f25582406697b9507c6fecc49eed907fcf26f78b722",
          "sha1": "543782e157c5008eac7c05747e800c3273d1c466",
          "md5": "c9fe22d7a78ee035bbd1740cbe39fa03"
        }
      ],
      "capabilities": [
        {
          "group": "technololgy.roughness.whitenoise",
          "name": "whitenoise-Common",
          "version": "1.21.1.4"
        },
        {
          "group": "technololgy.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.4-sources.jar",
          "url": "whitenoise-common-1.21.1.4-sources.jar",
          "size": 56489,
          "sha512": "c5db91d095e46cd3360a4ecff19ee34fae6dc622751793ede0726738baf7a6c1d60c060fc1421b79eac8d4c02ba2ec06658b58af06150df96bddb808b81bc7f0",
          "sha256": "8f72694c5e1cbd98ee6ee0b764803372ed6fe64032bedac804da3f91c9bbba76",
          "sha1": "d7321c74842371075df9d971b0d5dc940916a3de",
          "md5": "12493abcffd2b26e31a91576b1e7895d"
        }
      ],
      "capabilities": [
        {
          "group": "technololgy.roughness.whitenoise",
          "name": "whitenoise-Common",
          "version": "1.21.1.4"
        },
        {
          "group": "technololgy.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.4"
        }
      ]
    }
  ]
}
