{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.guidebook",
    "module": "guidebook-1.21.10-fabric",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "18.0.5"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "20.0.148"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "guidebook-1.21.10-fabric-1.1.1.jar",
          "url": "guidebook-1.21.10-fabric-1.1.1.jar",
          "size": 657421,
          "sha512": "0afa4f932ba8ba925bf6ef869009a9fa4202c68614bd2f5799ab84ab10847f943da63efdef76eca43c40dd98d285840a95f25c718a1d2f400496e007f96f4886",
          "sha256": "1157b99362604980c4b7ed2108dea6b7eba1210f29d52094cc5de88df3050350",
          "sha1": "35fa0a15c173656bb87b8179b6ff159d7bd569a1",
          "md5": "299d0d68bb34098774c7705c40247075"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook",
          "version": "1.1.1"
        },
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook-1.21.10-fabric",
          "version": "1.1.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "18.0.5"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "20.0.148"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.135.0+1.21.10"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.10-fabric",
          "version": {
            "requires": "2.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "guidebook-1.21.10-fabric-1.1.1.jar",
          "url": "guidebook-1.21.10-fabric-1.1.1.jar",
          "size": 657421,
          "sha512": "0afa4f932ba8ba925bf6ef869009a9fa4202c68614bd2f5799ab84ab10847f943da63efdef76eca43c40dd98d285840a95f25c718a1d2f400496e007f96f4886",
          "sha256": "1157b99362604980c4b7ed2108dea6b7eba1210f29d52094cc5de88df3050350",
          "sha1": "35fa0a15c173656bb87b8179b6ff159d7bd569a1",
          "md5": "299d0d68bb34098774c7705c40247075"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook",
          "version": "1.1.1"
        },
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook-1.21.10-fabric",
          "version": "1.1.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guidebook-1.21.10-fabric-1.1.1-sources.jar",
          "url": "guidebook-1.21.10-fabric-1.1.1-sources.jar",
          "size": 446211,
          "sha512": "f38953cf46bea90f5f5367005176948ba052ac71fdb7cffe0ee04fbafb32c2d8f65a5e9ec9a9ccbb4bcfbfe760b3f3f190761b686dad0c29efa250ebe8ee05c9",
          "sha256": "e686f85cd822e0ff2b09beb5f7b846cb84f72651f9bc675a6d213d61961e3fcb",
          "sha1": "5a964aee87d43795e157f7d496824bceb86bfa2c",
          "md5": "2d349ccf7d9c20ac7f1326d119ce0491"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook",
          "version": "1.1.1"
        },
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook-1.21.10-fabric",
          "version": "1.1.1"
        }
      ]
    }
  ]
}
