{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-1.21.9-common",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-common-2.0.1.jar",
          "url": "whitenoise-1.21.9-common-2.0.1.jar",
          "size": 161282,
          "sha512": "e4922b29cacd7bf5bf035f8b35276227239ac9ea3966afe948b247f55427c59a5e0d0b827f8f68455523c252e164f6a821f5af1dd5e2991b497a61f983f5310e",
          "sha256": "6530e62644f0e732b3b06f77b5582998e0cb49e13786617993ae48fe134d9d48",
          "sha1": "69bc2685e5f477549b34b0c19e5421736391051e",
          "md5": "4b8e5edb805379e4177b5df5edb69a94"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.1"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-common",
          "version": "2.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-1.21.9-common-2.0.1.jar",
          "url": "whitenoise-1.21.9-common-2.0.1.jar",
          "size": 161282,
          "sha512": "e4922b29cacd7bf5bf035f8b35276227239ac9ea3966afe948b247f55427c59a5e0d0b827f8f68455523c252e164f6a821f5af1dd5e2991b497a61f983f5310e",
          "sha256": "6530e62644f0e732b3b06f77b5582998e0cb49e13786617993ae48fe134d9d48",
          "sha1": "69bc2685e5f477549b34b0c19e5421736391051e",
          "md5": "4b8e5edb805379e4177b5df5edb69a94"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.1"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-common",
          "version": "2.0.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-common-2.0.1-sources.jar",
          "url": "whitenoise-1.21.9-common-2.0.1-sources.jar",
          "size": 76965,
          "sha512": "4932f49279073dfdd468e8c0c2634175e04349609bb395b9d9b366ad2d3c3ff1b7d97613427cfc151ebbc5cceb419e18ae4224aab1fa3a27e6f4575282748b2d",
          "sha256": "59984b0666556d4c8c0aa4d338dd2a4ad0f4b913a0de5c00e5a81137a07774a7",
          "sha1": "5778d3309ebbcbe9f3677beccd509e11e4556121",
          "md5": "aedf05309da8fabaa8472d3d4d1d35ce"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.1"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-common",
          "version": "2.0.1"
        }
      ]
    }
  ]
}
