{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-common",
    "version": "2.11.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.1-common-2.11.0.2.jar",
          "url": "homeostatic-1.21.1-common-2.11.0.2.jar",
          "size": 1613982,
          "sha512": "a6af1048c7c1b14217b840ee290767f53a0b2dbb448c8036348ad894ab55076c65a4d4bef1de4695b971f7c49c03608d23deeab2ac30ff02aee99b001adce87e",
          "sha256": "0bd0b1a56223f0cc8086328a4b65f96bcc5b6fadb3f73a450027f7074d551ac5",
          "sha1": "3df699e1fa797cbad680a073d4bce1da0feb4d17",
          "md5": "d28f1730c43be21eb5d2c641390ae981"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.2"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-common",
          "version": "2.11.0.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-1.21.1-common",
          "version": {
            "requires": "1.1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-common-2.11.0.2.jar",
          "url": "homeostatic-1.21.1-common-2.11.0.2.jar",
          "size": 1613982,
          "sha512": "a6af1048c7c1b14217b840ee290767f53a0b2dbb448c8036348ad894ab55076c65a4d4bef1de4695b971f7c49c03608d23deeab2ac30ff02aee99b001adce87e",
          "sha256": "0bd0b1a56223f0cc8086328a4b65f96bcc5b6fadb3f73a450027f7074d551ac5",
          "sha1": "3df699e1fa797cbad680a073d4bce1da0feb4d17",
          "md5": "d28f1730c43be21eb5d2c641390ae981"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.2"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-common",
          "version": "2.11.0.2"
        }
      ]
    }
  ]
}
