{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-common",
    "version": "1.0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.0.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.0.jar",
          "size": 132853,
          "sha512": "8f33926a443806bb6a7a8e0e51e03d9bacb3c9f158ce85c9e5cc23ff07bdca6b5f2759d336b66d00aa00944fb260cd56d28110cee840acc6c0a7564891925de0",
          "sha256": "57a6fd97017fe882d64df04e4befc8177c58b6a5ad175b3859607dce52adf397",
          "sha1": "066a66abc90dbff878f7dde144e3b9349bd2dc30",
          "md5": "8d1d216e16290f67fda96ceead7c30b1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.0"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.0.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.0.jar",
          "size": 132853,
          "sha512": "8f33926a443806bb6a7a8e0e51e03d9bacb3c9f158ce85c9e5cc23ff07bdca6b5f2759d336b66d00aa00944fb260cd56d28110cee840acc6c0a7564891925de0",
          "sha256": "57a6fd97017fe882d64df04e4befc8177c58b6a5ad175b3859607dce52adf397",
          "sha1": "066a66abc90dbff878f7dde144e3b9349bd2dc30",
          "md5": "8d1d216e16290f67fda96ceead7c30b1"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.0"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.0"
        }
      ]
    }
  ]
}
