{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-1.21.9-fabric",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-fabric-2.0.2.jar",
          "url": "whitenoise-1.21.9-fabric-2.0.2.jar",
          "size": 562820,
          "sha512": "d09cd540c4af61e35a0ac01536274aa30c83a28636e5ad248cdb6d3a50b41363e74527c776bbbcf152c77eda7852d1d9e3ace5258e066f05e8e218dc2afd21f4",
          "sha256": "c568b1b8dd60aca7c82cb377329b20cfbae258b95beffafb9c4f0de3311c15b9",
          "sha1": "99a7928ba5881decbfeb34390903289e4d8de921",
          "md5": "7d07350a03e69070c0e0737d9ef16fe7"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-fabric",
          "version": "2.0.2"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.0+1.21.9"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-1.21.9-fabric-2.0.2.jar",
          "url": "whitenoise-1.21.9-fabric-2.0.2.jar",
          "size": 562820,
          "sha512": "d09cd540c4af61e35a0ac01536274aa30c83a28636e5ad248cdb6d3a50b41363e74527c776bbbcf152c77eda7852d1d9e3ace5258e066f05e8e218dc2afd21f4",
          "sha256": "c568b1b8dd60aca7c82cb377329b20cfbae258b95beffafb9c4f0de3311c15b9",
          "sha1": "99a7928ba5881decbfeb34390903289e4d8de921",
          "md5": "7d07350a03e69070c0e0737d9ef16fe7"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-fabric",
          "version": "2.0.2"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-fabric-2.0.2-sources.jar",
          "url": "whitenoise-1.21.9-fabric-2.0.2-sources.jar",
          "size": 92392,
          "sha512": "d6f350e84ed2bc3796bae59d1aa8f1032f06763b0ed35f4cb9a4415f9e18dc3b2ee1d91a2a10fb52b92188ee7da13bbe0bf6f18a936cc1a5d43b172c98144451",
          "sha256": "30786a63a801a2bd1c72503e7307e1aa91d1cff6e1a34f0259468c14026f47ba",
          "sha1": "e0d5dce38f8b2ea5c723831f2fc353f0ec4e2312",
          "md5": "c9570ff8a87974ca8149deae79f28d91"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-fabric",
          "version": "2.0.2"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.2"
        }
      ]
    }
  ]
}
