{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-1.21.9-fabric",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-fabric-2.0.4.jar",
          "url": "whitenoise-1.21.9-fabric-2.0.4.jar",
          "size": 562865,
          "sha512": "3d547e49e5b2ed165d8608b6eb385caa875ddc3dbb4f0f6b6f65ca036407ef40edb93dad1e8e76e13e7903efc28cc191bf22a7a61b4a7b84621376e59a585312",
          "sha256": "983a20960dde23c505d074fc4465c337f6d66605503f8de9fb48bd7a3d7f4460",
          "sha1": "69bcb2e3cac7ae0c1b583aaa05b45c7c376cbb53",
          "md5": "f7c9c23c1ab2463603b5970f55585c94"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-fabric",
          "version": "2.0.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.0+1.21.9"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-1.21.9-fabric-2.0.4.jar",
          "url": "whitenoise-1.21.9-fabric-2.0.4.jar",
          "size": 562865,
          "sha512": "3d547e49e5b2ed165d8608b6eb385caa875ddc3dbb4f0f6b6f65ca036407ef40edb93dad1e8e76e13e7903efc28cc191bf22a7a61b4a7b84621376e59a585312",
          "sha256": "983a20960dde23c505d074fc4465c337f6d66605503f8de9fb48bd7a3d7f4460",
          "sha1": "69bcb2e3cac7ae0c1b583aaa05b45c7c376cbb53",
          "md5": "f7c9c23c1ab2463603b5970f55585c94"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-fabric",
          "version": "2.0.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-fabric-2.0.4-sources.jar",
          "url": "whitenoise-1.21.9-fabric-2.0.4-sources.jar",
          "size": 92427,
          "sha512": "fb35cdd4385fa7fd3f1c8804042ba734d9b14f87a2aa1c9cba4e444fd81792e42f016183b2d7d1e39eccb416e5b47b8893c979b3f220c7d4b23917630393cb8e",
          "sha256": "791932f5b1232fd0052644ac676c186041a63495cea2b1f48bf1d632c390be9e",
          "sha1": "10f94d0f07832b70a1e58a112079cef1260d57e3",
          "md5": "ffbc29fc3c1fdcdd24d170f9ad502394"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-fabric",
          "version": "2.0.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.4"
        }
      ]
    }
  ]
}
