{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-common",
    "version": "2.11.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.1-common-2.11.0.1.jar",
          "url": "homeostatic-1.21.1-common-2.11.0.1.jar",
          "size": 1389072,
          "sha512": "110a6118dc1e459e8fed30aeb8b58ec3b3ca8cc83ab7bb00253776e8fbd3e32bd79a61f47b9502d9f39459c820884820e981bc3defa01d047da73b7d202dbb8c",
          "sha256": "3c2612a2e4f8ab1d4cf953d8849fd09ddfffc00dde105dbf80370df0abb5221c",
          "sha1": "7504e2e96b16590ee37b35be5d8cdf550a50eae1",
          "md5": "e2e7344aa4e7fe6370eff34abfde8481"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.1"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-common",
          "version": "2.11.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-1.21.1-common",
          "version": {
            "requires": "1.0.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-common-2.11.0.1.jar",
          "url": "homeostatic-1.21.1-common-2.11.0.1.jar",
          "size": 1389072,
          "sha512": "110a6118dc1e459e8fed30aeb8b58ec3b3ca8cc83ab7bb00253776e8fbd3e32bd79a61f47b9502d9f39459c820884820e981bc3defa01d047da73b7d202dbb8c",
          "sha256": "3c2612a2e4f8ab1d4cf953d8849fd09ddfffc00dde105dbf80370df0abb5221c",
          "sha1": "7504e2e96b16590ee37b35be5d8cdf550a50eae1",
          "md5": "e2e7344aa4e7fe6370eff34abfde8481"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.1"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-common",
          "version": "2.11.0.1"
        }
      ]
    }
  ]
}
