{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-common",
    "version": "2.11.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.1-common-2.11.0.1.jar",
          "url": "homeostatic-1.21.1-common-2.11.0.1.jar",
          "size": 1389071,
          "sha512": "04b56f6b67e61f4f4dfa4cc1d37c721eb8265c4a31a49bff6ad2a6fc78de0f46195ec2c109bd5f2c9db8de7e8d3c465f283e765a277960a432e63cfaa8f2342e",
          "sha256": "25c8ba2ea54478102bc97f42a35cd4ad57a92c377d0f600ffa4d517ad4130956",
          "sha1": "dd7e7f3436014eb7c189fd487c82a7a5270911bb",
          "md5": "2728426e6794a6b753820ff167010304"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.1"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-common",
          "version": "2.11.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-1.21.1-common",
          "version": {
            "requires": "1.0.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-common-2.11.0.1.jar",
          "url": "homeostatic-1.21.1-common-2.11.0.1.jar",
          "size": 1389071,
          "sha512": "04b56f6b67e61f4f4dfa4cc1d37c721eb8265c4a31a49bff6ad2a6fc78de0f46195ec2c109bd5f2c9db8de7e8d3c465f283e765a277960a432e63cfaa8f2342e",
          "sha256": "25c8ba2ea54478102bc97f42a35cd4ad57a92c377d0f600ffa4d517ad4130956",
          "sha1": "dd7e7f3436014eb7c189fd487c82a7a5270911bb",
          "md5": "2728426e6794a6b753820ff167010304"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.1"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-common",
          "version": "2.11.0.1"
        }
      ]
    }
  ]
}
