{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.climatesettings",
    "module": "climatesettings-26.3-fabric",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "climatesettings-26.3-fabric-1.3.0.jar",
          "url": "climatesettings-26.3-fabric-1.3.0.jar",
          "size": 188009,
          "sha512": "d62a9c10f5527004c7a5d1252b37b7b22375c67e113113874a33b1b8bb5c95bf0b59ea91a23aa699f9c6fa318cdd8bbec808779675ce3b5a48e567d345e5efad",
          "sha256": "b775e5cb547385b584d7dba81bb16a2247d866fad05eeca008a77dc7fc520af9",
          "sha1": "f28b2ae15a68dfcd2bf285e3ecf14f97590d5cc3",
          "md5": "3bc4295f0a7e19a6bddb0f003380cf88"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings-26.3-fabric",
          "version": "1.3.0"
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.3-fabric",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "climatesettings-26.3-fabric-1.3.0.jar",
          "url": "climatesettings-26.3-fabric-1.3.0.jar",
          "size": 188009,
          "sha512": "d62a9c10f5527004c7a5d1252b37b7b22375c67e113113874a33b1b8bb5c95bf0b59ea91a23aa699f9c6fa318cdd8bbec808779675ce3b5a48e567d345e5efad",
          "sha256": "b775e5cb547385b584d7dba81bb16a2247d866fad05eeca008a77dc7fc520af9",
          "sha1": "f28b2ae15a68dfcd2bf285e3ecf14f97590d5cc3",
          "md5": "3bc4295f0a7e19a6bddb0f003380cf88"
        }
      ]
    }
  ]
}
