{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-1.21.10-fabric",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "18.0.5"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "20.0.148"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "handbook-1.21.10-fabric-1.2.1.jar",
          "url": "handbook-1.21.10-fabric-1.2.1.jar",
          "size": 656564,
          "sha512": "47f340019d7bebdc444cf940979508f81e7585dfff1b0f109db58ddc3840d58fc88549af1baae7c2b17a7696ee7a61c6ebdde489927e60cf8ce3b17ab9a71d9d",
          "sha256": "18fd2138a1ca5b795c5ff46b3206aa40f77b42d3653557b9c5b4d0d7ea0962c3",
          "sha1": "81e554e9656a9c7bde4b43dc3ff1fc2848eea1ef",
          "md5": "a4864c90ea2ec91757d191c6b7b02f8b"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-1.21.10-fabric",
          "version": "1.2.1"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "18.0.5"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "20.0.148"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.135.0+1.21.10"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.10-fabric",
          "version": {
            "requires": "2.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-1.21.10-fabric-1.2.1.jar",
          "url": "handbook-1.21.10-fabric-1.2.1.jar",
          "size": 656564,
          "sha512": "47f340019d7bebdc444cf940979508f81e7585dfff1b0f109db58ddc3840d58fc88549af1baae7c2b17a7696ee7a61c6ebdde489927e60cf8ce3b17ab9a71d9d",
          "sha256": "18fd2138a1ca5b795c5ff46b3206aa40f77b42d3653557b9c5b4d0d7ea0962c3",
          "sha1": "81e554e9656a9c7bde4b43dc3ff1fc2848eea1ef",
          "md5": "a4864c90ea2ec91757d191c6b7b02f8b"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-1.21.10-fabric",
          "version": "1.2.1"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-1.21.10-fabric-1.2.1-sources.jar",
          "url": "handbook-1.21.10-fabric-1.2.1-sources.jar",
          "size": 445725,
          "sha512": "6d5ebb458497a8d32b9150915a9ab0e99cb788a3c498c52c639499b57144341a360d4eccf359bfab770eb85c2bc40fd0dc4fb610b834c4d723137715d4deec6d",
          "sha256": "affd65d2386452c53e526349625d02dbb15eb0131ea6086918e7f4fb406d6b90",
          "sha1": "33565265e234be60966ff963fd14302ed5a7f7fd",
          "md5": "3de11aacfc63c21d0cc60bde8e296989"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-1.21.10-fabric",
          "version": "1.2.1"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.1"
        }
      ]
    }
  ]
}
