{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-fabric",
    "version": "1.21.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.1.5.jar",
          "url": "whitenoise-fabric-1.21.1.5.jar",
          "size": 365927,
          "sha512": "8210ac75a6e3e9fe7292462f4dfc3a3161a69d50489054c9b28f2866ba635eb252f05958d0ebce6b32d8325a300f63e9fd055fa08fdc39bf42bc1942b82289b1",
          "sha256": "8709fd8c4b59c35bc3e30d4933dd9694cfa787a4f2bdc594c2ecc381e62a9a6f",
          "sha1": "3c488f158f080adfd6d398e13732d4fc8e910ac7",
          "md5": "1652e700246e80b1bcf069982f103266"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.1.5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.7"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-fabric-1.21.1.5.jar",
          "url": "whitenoise-fabric-1.21.1.5.jar",
          "size": 365927,
          "sha512": "8210ac75a6e3e9fe7292462f4dfc3a3161a69d50489054c9b28f2866ba635eb252f05958d0ebce6b32d8325a300f63e9fd055fa08fdc39bf42bc1942b82289b1",
          "sha256": "8709fd8c4b59c35bc3e30d4933dd9694cfa787a4f2bdc594c2ecc381e62a9a6f",
          "sha1": "3c488f158f080adfd6d398e13732d4fc8e910ac7",
          "md5": "1652e700246e80b1bcf069982f103266"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.1.5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.1.5-sources.jar",
          "url": "whitenoise-fabric-1.21.1.5-sources.jar",
          "size": 70253,
          "sha512": "8b3720d2fbb776b17bc7908e07793804716cf5e013fd5c17d01956b7de9839ceaca91ce2d933534ff9afd6eb81f30d35a5b70111bdee8968b16c0be3810c26b1",
          "sha256": "6270a933537c25397b1ecba71fb33a787561dadab5a7b1eae26dd571f2092df9",
          "sha1": "8e9d69036612d93cb5575d73ac0090d14d6a274c",
          "md5": "193d64d2ff8ef785cbbea32efcfdbade"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.1.5"
        }
      ]
    }
  ]
}
