{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.climatesettings",
    "module": "climatesettings-26.1.2-fabric",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "climatesettings-26.1.2-fabric-1.2.1.jar",
          "url": "climatesettings-26.1.2-fabric-1.2.1.jar",
          "size": 182317,
          "sha512": "0f97d020a7eb937ef4d8da5bb21a203b57d3982cec871148089ca683d65f2afe6c357e59ebc18ab100b9e96c86c28121d5d4279ae51dffd7d0c520661fe2d7ed",
          "sha256": "dc38b827472fcf36c7a084f575d4f08b135593b02c238de085d9d96be1eeef0d",
          "sha1": "d49fc8e92047d7c1bc976d1da1a838e76de55220",
          "md5": "f7d95f94809fe6dd33989032ad668d77"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings-26.1.2-fabric",
          "version": "1.2.1"
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings",
          "version": "1.2.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.2"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.2-fabric",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "climatesettings-26.1.2-fabric-1.2.1.jar",
          "url": "climatesettings-26.1.2-fabric-1.2.1.jar",
          "size": 182317,
          "sha512": "0f97d020a7eb937ef4d8da5bb21a203b57d3982cec871148089ca683d65f2afe6c357e59ebc18ab100b9e96c86c28121d5d4279ae51dffd7d0c520661fe2d7ed",
          "sha256": "dc38b827472fcf36c7a084f575d4f08b135593b02c238de085d9d96be1eeef0d",
          "sha1": "d49fc8e92047d7c1bc976d1da1a838e76de55220",
          "md5": "f7d95f94809fe6dd33989032ad668d77"
        }
      ]
    }
  ]
}
