{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-fabric",
    "version": "1.21.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.4.jar",
          "url": "whitenoise-fabric-1.21.8.4.jar",
          "size": 536227,
          "sha512": "32077849024f88084878c908673a04140a81267c93580d81885e3c2731d4504a6ccba0a6753b5a6c30b274cd694eb7c253425005c4a42493c66eacb232f45338",
          "sha256": "01c6c1ed95dee1a466ad462e167380b98914b16d015e787dca62d006bf396bf1",
          "sha1": "020f686236b826c7d737d44fb41637e8593dd126",
          "md5": "81134a85ef828d04754c499a0f9214ec"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.133.4+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.4.jar",
          "url": "whitenoise-fabric-1.21.8.4.jar",
          "size": 536227,
          "sha512": "32077849024f88084878c908673a04140a81267c93580d81885e3c2731d4504a6ccba0a6753b5a6c30b274cd694eb7c253425005c4a42493c66eacb232f45338",
          "sha256": "01c6c1ed95dee1a466ad462e167380b98914b16d015e787dca62d006bf396bf1",
          "sha1": "020f686236b826c7d737d44fb41637e8593dd126",
          "md5": "81134a85ef828d04754c499a0f9214ec"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.4-sources.jar",
          "url": "whitenoise-fabric-1.21.8.4-sources.jar",
          "size": 71775,
          "sha512": "b107f2a8c310763e2459277baf093e7c462d1d86be15f9fdd1668e49b91fb82515e1273405d9f52ea813e62e03d8bf7b73985b94a53a26e8c42360239cc2d28b",
          "sha256": "3ee9f1935a9efb6d97558086c385dbb2f8150c23872b68cba208af8599b3a85c",
          "sha1": "b80b900586e9d4d0a3742edceae20c04e6bd261e",
          "md5": "3f633109a176edc5fd0ddb8cac34d0d5"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.4"
        }
      ]
    }
  ]
}
