{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-26.3-fabric",
    "version": "1.2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-26.3-fabric-1.2.0.3.jar",
          "url": "homeostaticseasons-26.3-fabric-1.2.0.3.jar",
          "size": 1024129,
          "sha512": "dea9bcef462adec6bff81cc3bfaeea7313caeca8dcf5b6e3c98ec19a7b0e4d015ea1aee6c02667ff1500451c1bf447db37e6470b61b983efa25ab2aaad3a7d74",
          "sha256": "42b6e7bc03a0513589d2a059df35624d4a8fa7dedfbeacdf25d1e88c4ebd4cd7",
          "sha1": "5d4668b7cf022809b853a057f63b8b354583062e",
          "md5": "063a9dea8dc974b512496d0d72f4d437"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.2.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-26.3-fabric",
          "version": "1.2.0.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.3-fabric",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.3-fabric",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-26.3-fabric-1.2.0.3.jar",
          "url": "homeostaticseasons-26.3-fabric-1.2.0.3.jar",
          "size": 1024129,
          "sha512": "dea9bcef462adec6bff81cc3bfaeea7313caeca8dcf5b6e3c98ec19a7b0e4d015ea1aee6c02667ff1500451c1bf447db37e6470b61b983efa25ab2aaad3a7d74",
          "sha256": "42b6e7bc03a0513589d2a059df35624d4a8fa7dedfbeacdf25d1e88c4ebd4cd7",
          "sha1": "5d4668b7cf022809b853a057f63b8b354583062e",
          "md5": "063a9dea8dc974b512496d0d72f4d437"
        }
      ]
    }
  ]
}
