{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-26.1.1-common",
    "version": "1.1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-26.1.1-common-1.1.0.7.jar",
          "url": "homeostaticseasons-26.1.1-common-1.1.0.7.jar",
          "size": 384118,
          "sha512": "e490dc80f69dc435dd842e5558ef3a8a0b4ca0c3c8e455ebfc14fdd7a8315c9ea84bf12e9a25dc44ca066be04e9e5552c9f607b248bb778f5e102289c0a7013f",
          "sha256": "8d32092ea0cdd6c1106a028e0adee2d586acf513edfd94c8e83a92178a904f0a",
          "sha1": "0d1a78dab3100a503a81e89581b684d90b5ca247",
          "md5": "d356189fee93840c4c16bc7989117c41"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-26.1.1-common",
          "version": "1.1.0.7"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.1.0.7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.1.1-common",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-26.1.1-common-1.1.0.7.jar",
          "url": "homeostaticseasons-26.1.1-common-1.1.0.7.jar",
          "size": 384118,
          "sha512": "e490dc80f69dc435dd842e5558ef3a8a0b4ca0c3c8e455ebfc14fdd7a8315c9ea84bf12e9a25dc44ca066be04e9e5552c9f607b248bb778f5e102289c0a7013f",
          "sha256": "8d32092ea0cdd6c1106a028e0adee2d586acf513edfd94c8e83a92178a904f0a",
          "sha1": "0d1a78dab3100a503a81e89581b684d90b5ca247",
          "md5": "d356189fee93840c4c16bc7989117c41"
        }
      ]
    }
  ]
}
