{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-26.3-common",
    "version": "1.2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-26.3-common-1.2.0.4.jar",
          "url": "homeostaticseasons-26.3-common-1.2.0.4.jar",
          "size": 387936,
          "sha512": "c5dcbbc6e5a3640f778ba07a6ca622888cee3498a16d991509fa0ec496c4ae41bad8239a1aa65176681fe1a9de83d38a8ac5fde21e0b74533805a4a25803239b",
          "sha256": "e06b475cdaae771260dd1352f06096e9f7c8627c51f04eb827f8d236613a8109",
          "sha1": "a09168af9dde482540a01b54d21e620c35b3b245",
          "md5": "7f935b5868afd278473aa05db5d76eb7"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.2.0.4"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-26.3-common",
          "version": "1.2.0.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.3-common",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.3-common",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-26.3-common-1.2.0.4.jar",
          "url": "homeostaticseasons-26.3-common-1.2.0.4.jar",
          "size": 387936,
          "sha512": "c5dcbbc6e5a3640f778ba07a6ca622888cee3498a16d991509fa0ec496c4ae41bad8239a1aa65176681fe1a9de83d38a8ac5fde21e0b74533805a4a25803239b",
          "sha256": "e06b475cdaae771260dd1352f06096e9f7c8627c51f04eb827f8d236613a8109",
          "sha1": "a09168af9dde482540a01b54d21e620c35b3b245",
          "md5": "7f935b5868afd278473aa05db5d76eb7"
        }
      ]
    }
  ]
}
