{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.2-fabric",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.2-fabric-1.3.1.jar",
          "url": "handbook-26.1.2-fabric-1.3.1.jar",
          "size": 651279,
          "sha512": "2f39caffe144cec0b9d6be6e0c9462ad2e50877c8f2309cdbbcf0af1ceee6a14dd8987922f34dd6b54dcef015610fdd7dbf7df19668990dee1f7aec14c522a61",
          "sha256": "e357946bf8ec679049472ca90440f116da2bbdb6a96f5d21d65c359faa2ae6a8",
          "sha1": "41610a4786e854c0c18c8d676bf743dcccc06e1a",
          "md5": "bc886085b61d8d528914d0833877b087"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.1"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.2-fabric",
          "version": "1.3.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.2-fabric",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.2-fabric-1.3.1.jar",
          "url": "handbook-26.1.2-fabric-1.3.1.jar",
          "size": 651279,
          "sha512": "2f39caffe144cec0b9d6be6e0c9462ad2e50877c8f2309cdbbcf0af1ceee6a14dd8987922f34dd6b54dcef015610fdd7dbf7df19668990dee1f7aec14c522a61",
          "sha256": "e357946bf8ec679049472ca90440f116da2bbdb6a96f5d21d65c359faa2ae6a8",
          "sha1": "41610a4786e854c0c18c8d676bf743dcccc06e1a",
          "md5": "bc886085b61d8d528914d0833877b087"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.1"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.2-fabric",
          "version": "1.3.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.2-fabric-1.3.1-sources.jar",
          "url": "handbook-26.1.2-fabric-1.3.1-sources.jar",
          "size": 435791,
          "sha512": "51c41e736bb3852ed5cceac1070ceee9c7f771a5fe30b690b6a006377f0361a591bf7d8ad8c3eccc74305cca5174c21c702860ae1465086482255ab8d58cbfc5",
          "sha256": "a1d3668da3846f29c8b5a471c350e0f87b9e1ed63de736e387ce6927582a3ade",
          "sha1": "cf1f80485e557107edc7bd3014a2bfbee92b5c7d",
          "md5": "2c4960c20a642f86388b5707b74f08a0"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.1"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.2-fabric",
          "version": "1.3.1"
        }
      ]
    }
  ]
}
