{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-fabric",
    "version": "1.21.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.3.jar",
          "url": "whitenoise-fabric-1.21.8.3.jar",
          "size": 535966,
          "sha512": "20261a737bf55c160ed9a69bd85a048cfaf915375361e4a774fbb0c8e4debf56f38369704031afaddf0352d62ae1d1dbd9f3e7a56e11e2c985c43d425b87954b",
          "sha256": "b50b0af09f3fa5d12a8ff404b99ef2fa51db941d3069520d0978dc00c670a2b7",
          "sha1": "80ac576cd97090c29e37af355ac8b0da60fa648f",
          "md5": "4e1548fa7f4d706001737b8811e8315e"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.3"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.133.4+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.3.jar",
          "url": "whitenoise-fabric-1.21.8.3.jar",
          "size": 535966,
          "sha512": "20261a737bf55c160ed9a69bd85a048cfaf915375361e4a774fbb0c8e4debf56f38369704031afaddf0352d62ae1d1dbd9f3e7a56e11e2c985c43d425b87954b",
          "sha256": "b50b0af09f3fa5d12a8ff404b99ef2fa51db941d3069520d0978dc00c670a2b7",
          "sha1": "80ac576cd97090c29e37af355ac8b0da60fa648f",
          "md5": "4e1548fa7f4d706001737b8811e8315e"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.3"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.3-sources.jar",
          "url": "whitenoise-fabric-1.21.8.3-sources.jar",
          "size": 71695,
          "sha512": "f067e0ef42eff181d8f458e50cdb1f1981d95f49b35c2cc5734c0fe984e60fbeb71e1edf263936fcbeae41cf04d1acb6acf68895e4b8c69b862dcab669dd2165",
          "sha256": "65c27ef7752ac76f7b2d0f62cce58b6520bf14d5fa37f18abb40f1a5c8617b1f",
          "sha1": "282a4e45a9cb1693980d7c69542e8f259deab746",
          "md5": "41b0feb79faff3b354b8f50a7c520369"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.3"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.3"
        }
      ]
    }
  ]
}
