{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-fabric",
    "version": "2.11.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.8.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.8.jar",
          "size": 2965141,
          "sha512": "e1b6971706908f9e6db2586c068029385caa4ce284434956d5a2b726e72ab939df8930aef504b188f5524593ac8b8e9887fc3f8ee1ab5650b28ea49c0fa778a4",
          "sha256": "04197b95bf85e20024fafc0ebefa67ff43a0a400101796d10f7dabb9545e5709",
          "sha1": "b3a8a7c58e4c1386f0039c3ef5eb681f2060c3f9",
          "md5": "8ecdf119201ef29fa5bc57a1d99dc2ef"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.11.0.8"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-1.21.1-fabric",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-1.21.1-fabric",
          "version": {
            "requires": "1.1.0.4"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.8.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.8.jar",
          "size": 2965141,
          "sha512": "e1b6971706908f9e6db2586c068029385caa4ce284434956d5a2b726e72ab939df8930aef504b188f5524593ac8b8e9887fc3f8ee1ab5650b28ea49c0fa778a4",
          "sha256": "04197b95bf85e20024fafc0ebefa67ff43a0a400101796d10f7dabb9545e5709",
          "sha1": "b3a8a7c58e4c1386f0039c3ef5eb681f2060c3f9",
          "md5": "8ecdf119201ef29fa5bc57a1d99dc2ef"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.11.0.8"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.8"
        }
      ]
    }
  ]
}
