{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.11-fabric",
    "version": "2.11.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.11-fabric-2.11.0.2.jar",
          "url": "homeostatic-1.21.11-fabric-2.11.0.2.jar",
          "size": 2970305,
          "sha512": "0c7bf6755bfbf94a7592a20a74342247fbb84831adcb51d7cce493f5c55001dcee956d0293649066247f6f488cb52617257010970175b8cd07aa62020722d4f2",
          "sha256": "873456526fc3d18e9ae6e82f6858042a6ff8050366538fc629c1fb6053959ab3",
          "sha1": "3eba82f0994e11678701e285d93ca9355777515e",
          "md5": "67284cd33584eae06ef0c47fe63fb92e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.11-fabric",
          "version": "2.11.0.2"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.4+1.21.11"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.11-fabric",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.11-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-1.21.11-fabric",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-1.21.11-fabric",
          "version": {
            "requires": "1.1.0.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.11-fabric-2.11.0.2.jar",
          "url": "homeostatic-1.21.11-fabric-2.11.0.2.jar",
          "size": 2970305,
          "sha512": "0c7bf6755bfbf94a7592a20a74342247fbb84831adcb51d7cce493f5c55001dcee956d0293649066247f6f488cb52617257010970175b8cd07aa62020722d4f2",
          "sha256": "873456526fc3d18e9ae6e82f6858042a6ff8050366538fc629c1fb6053959ab3",
          "sha1": "3eba82f0994e11678701e285d93ca9355777515e",
          "md5": "67284cd33584eae06ef0c47fe63fb92e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.11-fabric",
          "version": "2.11.0.2"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.2"
        }
      ]
    }
  ]
}
