{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-common",
    "version": "1.2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.2.0.0.jar",
          "url": "homeostaticseasons-1.21.1-common-1.2.0.0.jar",
          "size": 383337,
          "sha512": "ac66fabc0d4f0e8cbdd1da61920aeee954d29c440edcb100a9f2e6b375945337f6308ff32741f1f604c8155ac3bd2f4c08288bcd112dd0e0872ecc74acdb4c44",
          "sha256": "3c3956eb6ff88755cc48339365da487fd694ef499d46df769166bc7244627640",
          "sha1": "5fc92dab85113d97545baecd19464e0a735edc76",
          "md5": "766eb4f2e20278a5c1db8f25e15c0249"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.2.0.0"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.2.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.2.0.0.jar",
          "url": "homeostaticseasons-1.21.1-common-1.2.0.0.jar",
          "size": 383337,
          "sha512": "ac66fabc0d4f0e8cbdd1da61920aeee954d29c440edcb100a9f2e6b375945337f6308ff32741f1f604c8155ac3bd2f4c08288bcd112dd0e0872ecc74acdb4c44",
          "sha256": "3c3956eb6ff88755cc48339365da487fd694ef499d46df769166bc7244627640",
          "sha1": "5fc92dab85113d97545baecd19464e0a735edc76",
          "md5": "766eb4f2e20278a5c1db8f25e15c0249"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.2.0.0"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.2.0.0"
        }
      ]
    }
  ]
}
