{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-26.1-common",
    "version": "2.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-26.1-common-2.0.7.jar",
          "url": "whitenoise-26.1-common-2.0.7.jar",
          "size": 161590,
          "sha512": "0849e0e35a8842c2c63e6b38a7672feed420cf33b43adc819fea5a7cbc2ead49853ab07244a113b4f8df2a5cbfbf686296ad5572163e2671bd90ffcf476d6719",
          "sha256": "f085373664ad1d15f95b495116e4fa0e21702f65a5e49bc8793e7e8205106e5e",
          "sha1": "40134f546ffb7e5ed951d86fafda884a3a54fe04",
          "md5": "b4805520cd3d8367496788a1159e0787"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-26.1-common",
          "version": "2.0.7"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-26.1-common-2.0.7.jar",
          "url": "whitenoise-26.1-common-2.0.7.jar",
          "size": 161590,
          "sha512": "0849e0e35a8842c2c63e6b38a7672feed420cf33b43adc819fea5a7cbc2ead49853ab07244a113b4f8df2a5cbfbf686296ad5572163e2671bd90ffcf476d6719",
          "sha256": "f085373664ad1d15f95b495116e4fa0e21702f65a5e49bc8793e7e8205106e5e",
          "sha1": "40134f546ffb7e5ed951d86fafda884a3a54fe04",
          "md5": "b4805520cd3d8367496788a1159e0787"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-26.1-common-2.0.7-sources.jar",
          "url": "whitenoise-26.1-common-2.0.7-sources.jar",
          "size": 77099,
          "sha512": "deb363ab6d7b05afeeaf41d038e6204e90405c303fb91a655f8867bab7554d91a00aea10341ef21b81c4b91f03684b1d2733e221e220d1b13c6ee9b0a1789f52",
          "sha256": "5aaf83eaf11efe2c1ae32dba42d90681f5886a2a37de533716595532b5005ea4",
          "sha1": "7972028add9f1321e74b333dd554d44b413d207b",
          "md5": "97db101f317711b39a7dc76856771cc3"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-26.1-common",
          "version": "2.0.7"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.7"
        }
      ]
    }
  ]
}
