{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.3-common",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.3-common-1.3.4.jar",
          "url": "handbook-26.3-common-1.3.4.jar",
          "size": 628458,
          "sha512": "cb9de47c6128c85143bef1191e7b876ebb2be191d3e69fb93d2e83ba87b0694fb3605c891e34def6a9467fb265d1ac1cd56e800eb7637125403030296973f69d",
          "sha256": "b2fe9e6d06307de70a6581aab2241ba2ac11c827f3b8ce38e9806e8cb63033fc",
          "sha1": "fa928dff31096d4c674f2492ea956c6501267f26",
          "md5": "031a04ea3f5c98d8c752c1bec1b47594"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.3-common",
          "version": "1.3.4"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.3-common",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.3-common-1.3.4.jar",
          "url": "handbook-26.3-common-1.3.4.jar",
          "size": 628458,
          "sha512": "cb9de47c6128c85143bef1191e7b876ebb2be191d3e69fb93d2e83ba87b0694fb3605c891e34def6a9467fb265d1ac1cd56e800eb7637125403030296973f69d",
          "sha256": "b2fe9e6d06307de70a6581aab2241ba2ac11c827f3b8ce38e9806e8cb63033fc",
          "sha1": "fa928dff31096d4c674f2492ea956c6501267f26",
          "md5": "031a04ea3f5c98d8c752c1bec1b47594"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.3-common",
          "version": "1.3.4"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.3-common-1.3.4-sources.jar",
          "url": "handbook-26.3-common-1.3.4-sources.jar",
          "size": 425687,
          "sha512": "553c9576de7a455a9ceadbdd0cc5194a65673be08aec347b5a1ba5217a220e20e687bccba568fff9716452c6bddf96abd002e4620badc5f8e45b1c005afbf3f9",
          "sha256": "0de60510228951b4264688d577685c957e253ec2fe516460db57f82039737979",
          "sha1": "5429d99cd5e9feab6d341071457477eca8977b0d",
          "md5": "043237797547925c1c2323e58cbc693e"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.3-common",
          "version": "1.3.4"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.4"
        }
      ]
    }
  ]
}
