{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.3-fabric",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.3-fabric-1.3.4.jar",
          "url": "handbook-26.3-fabric-1.3.4.jar",
          "size": 662679,
          "sha512": "e82f81688654821fba6bf9e97d6c9691d7f3f97473e4a8296d285a79ef7d57ec87872d301b51d74952461559918ec5b6b09d4624ee5192d276bc8d7b1823cb62",
          "sha256": "3580ef13c69854fd99200fb73cec77fff2b82ae59ef72ff5d40e52767c0e6a1c",
          "sha1": "d6832f9f5ebf76b6178bc4cac9150b0192197d52",
          "md5": "57addee538db0f4f51cf9293d06ac354"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.3-fabric",
          "version": "1.3.4"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.6+26.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.3-fabric",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.3-fabric-1.3.4.jar",
          "url": "handbook-26.3-fabric-1.3.4.jar",
          "size": 662679,
          "sha512": "e82f81688654821fba6bf9e97d6c9691d7f3f97473e4a8296d285a79ef7d57ec87872d301b51d74952461559918ec5b6b09d4624ee5192d276bc8d7b1823cb62",
          "sha256": "3580ef13c69854fd99200fb73cec77fff2b82ae59ef72ff5d40e52767c0e6a1c",
          "sha1": "d6832f9f5ebf76b6178bc4cac9150b0192197d52",
          "md5": "57addee538db0f4f51cf9293d06ac354"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.3-fabric",
          "version": "1.3.4"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.3-fabric-1.3.4-sources.jar",
          "url": "handbook-26.3-fabric-1.3.4-sources.jar",
          "size": 440913,
          "sha512": "a801ca8c55a17f26cfd136d455b8412eb0dec36908b3135cbb729e0c192bfa2dfa0c664b669c734c32c631126b8fa4ace3a93969153365bf8242b6c396de14e0",
          "sha256": "b77bb79478aa16e064f45d472067b23612f7f576240257156f8a2ec27ca10fcc",
          "sha1": "90d7e8cd7123f12f6c15e966ed95ab0fcb4460b6",
          "md5": "f02c106fd10cf33fffbb2e6cf00d866d"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.3-fabric",
          "version": "1.3.4"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.4"
        }
      ]
    }
  ]
}
