{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-fabric",
    "version": "1.21.1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.1.15.jar",
          "url": "whitenoise-fabric-1.21.1.15.jar",
          "size": 532282,
          "sha512": "11100b1dc576665aaf78881916d0927d02298103698e889a4a1b6de894c918e593d9844ee12ebeadc8a4f5334c13cb576b01af54c98879200c1997afd79257f5",
          "sha256": "2791adcfea3b4418b4e1b04e958540755e70b45036ba9d73770694541d5422a5",
          "sha1": "933da1369dfa93307e3d4c905d8d412fb962fcc4",
          "md5": "8d6f92955492a777ef319f5a7a90e536"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.1.15"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-fabric-1.21.1.15.jar",
          "url": "whitenoise-fabric-1.21.1.15.jar",
          "size": 532282,
          "sha512": "11100b1dc576665aaf78881916d0927d02298103698e889a4a1b6de894c918e593d9844ee12ebeadc8a4f5334c13cb576b01af54c98879200c1997afd79257f5",
          "sha256": "2791adcfea3b4418b4e1b04e958540755e70b45036ba9d73770694541d5422a5",
          "sha1": "933da1369dfa93307e3d4c905d8d412fb962fcc4",
          "md5": "8d6f92955492a777ef319f5a7a90e536"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.1.15"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.1.15-sources.jar",
          "url": "whitenoise-fabric-1.21.1.15-sources.jar",
          "size": 70335,
          "sha512": "5e33dd6601dcf9eac6fae4081671a28a8c3f6b7db51fd01eb802965395c1dcb7ab0fa2b99ea07939c5d0b1990a6c0977aa9fc227a5f63d50c7e19541e569344c",
          "sha256": "4d35ee1d5882ae3aff9e7484d1b910cd754cfce0542bfc4a80d6cd05e509262b",
          "sha1": "f72824e732fcd1d9e9eb9642c21a9f62a227fdf0",
          "md5": "5af59bdd58c7ff4a983fb970fbaf7406"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.1.15"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.15"
        }
      ]
    }
  ]
}
