{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.climatesettings",
    "module": "climatesettings-26.1.1-fabric",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "climatesettings-26.1.1-fabric-1.2.1.jar",
          "url": "climatesettings-26.1.1-fabric-1.2.1.jar",
          "size": 182449,
          "sha512": "b1160f9ad36698f140631c319f31292eeddb4492b2c44c1255fdb8d6040d28b9e181f645016d2d9657fff4d25925c5d2b77a9019c35e279786a62c3b7a4d74f8",
          "sha256": "a86e4347c258062b8f93ce488cb06dc332ce17c1ae1f8bf1529683cf7818ffbb",
          "sha1": "109aa083ba1b0bb7227e6b839bdb1f171e0dc5a9",
          "md5": "fc512f2e956f646e0d3c9ccb1c6d3132"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings-26.1.1-fabric",
          "version": "1.2.1"
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings",
          "version": "1.2.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.2+26.1.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "climatesettings-26.1.1-fabric-1.2.1.jar",
          "url": "climatesettings-26.1.1-fabric-1.2.1.jar",
          "size": 182449,
          "sha512": "b1160f9ad36698f140631c319f31292eeddb4492b2c44c1255fdb8d6040d28b9e181f645016d2d9657fff4d25925c5d2b77a9019c35e279786a62c3b7a4d74f8",
          "sha256": "a86e4347c258062b8f93ce488cb06dc332ce17c1ae1f8bf1529683cf7818ffbb",
          "sha1": "109aa083ba1b0bb7227e6b839bdb1f171e0dc5a9",
          "md5": "fc512f2e956f646e0d3c9ccb1c6d3132"
        }
      ]
    }
  ]
}
