{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-1.21.1-fabric",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-1.21.1-fabric-1.0.0.jar",
          "url": "whitenoise-1.21.1-fabric-1.0.0.jar",
          "size": 536142,
          "sha512": "ad7da8490fa7142a6f7a496739f328f0fd9e10f694fc2732ed752f1be4e6061fb6176c02914f5cdc508594203411f77d90413b36231269e6e967695c2a59084e",
          "sha256": "f58b22f61d29ff3e757ec2db7b4a056c8d1f08c640d0b21c769b4bfaad6f7967",
          "sha1": "dac7a72411cc1306053b9dba0265fb1b96f4b1ba",
          "md5": "ba0791139efd2f7c8f01e1dbc426a33e"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.0.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.1-fabric",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-1.21.1-fabric-1.0.0.jar",
          "url": "whitenoise-1.21.1-fabric-1.0.0.jar",
          "size": 536142,
          "sha512": "ad7da8490fa7142a6f7a496739f328f0fd9e10f694fc2732ed752f1be4e6061fb6176c02914f5cdc508594203411f77d90413b36231269e6e967695c2a59084e",
          "sha256": "f58b22f61d29ff3e757ec2db7b4a056c8d1f08c640d0b21c769b4bfaad6f7967",
          "sha1": "dac7a72411cc1306053b9dba0265fb1b96f4b1ba",
          "md5": "ba0791139efd2f7c8f01e1dbc426a33e"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.0.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.1-fabric",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-1.21.1-fabric-1.0.0-sources.jar",
          "url": "whitenoise-1.21.1-fabric-1.0.0-sources.jar",
          "size": 71473,
          "sha512": "cc5da83da0622cd02a89e1477d918f19346d47c01ce8e67856d0ae7f20af2254b2d3f197b49a9a47c94b1dc37f84b254c153529ec7bff8b0482330a8921fcf47",
          "sha256": "7d81bb9cebe1131ce65387d5d472c9244e6908c9ec516449ae784b970e219142",
          "sha1": "9377b7d1363f09f9b897ca89f7655b6b537add88",
          "md5": "d3ccb98cb07d71eb8be47c7c27ccedd3"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.0.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.1-fabric",
          "version": "1.0.0"
        }
      ]
    }
  ]
}
