{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-fabric",
    "version": "2.12.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.12.0.0.jar",
          "url": "homeostatic-1.21.1-fabric-2.12.0.0.jar",
          "size": 2966193,
          "sha512": "3f3bb3c9016806ffd3a5af51f6893c4fa39a9cfa6db32a2e0f2d14fa878c111e7cb1251e1d5b31b06663663870b517ad470d9c535aab1d50951c9922edc0d135",
          "sha256": "0076474edd8006783b4af17817d3da6423c6db0b44f50ab2e798af532b0db3ee",
          "sha1": "ad2a032721f66ca812a99df87d2e5cb9b6ec0da9",
          "md5": "8d478b4be365418d4dab61c56abcb8e5"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.12.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.12.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.11+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-1.21.1-fabric",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-1.21.1-fabric",
          "version": {
            "requires": "1.2.0.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.12.0.0.jar",
          "url": "homeostatic-1.21.1-fabric-2.12.0.0.jar",
          "size": 2966193,
          "sha512": "3f3bb3c9016806ffd3a5af51f6893c4fa39a9cfa6db32a2e0f2d14fa878c111e7cb1251e1d5b31b06663663870b517ad470d9c535aab1d50951c9922edc0d135",
          "sha256": "0076474edd8006783b4af17817d3da6423c6db0b44f50ab2e798af532b0db3ee",
          "sha1": "ad2a032721f66ca812a99df87d2e5cb9b6ec0da9",
          "md5": "8d478b4be365418d4dab61c56abcb8e5"
        }
      ]
    }
  ]
}
