{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.3-fabric",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.3-fabric-1.3.3.jar",
          "url": "handbook-26.3-fabric-1.3.3.jar",
          "size": 662675,
          "sha512": "223885448246898659989b35941853ca4c02db4b372e6acfc6b33a5b46e07548374501c35aeecf666e471f6d83e50a2bec5abfe8e8da0e0fd91d86a176ebdf72",
          "sha256": "a786a2483d41290544bc14f10117dc06b8ffce44a27e1d59657a1f06db679563",
          "sha1": "24ceabd4980d14d983b73d7e4dcaf7707ef350fe",
          "md5": "a584b0e7f78a230c088248e98a6ca612"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.3"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.3-fabric",
          "version": "1.3.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.6+26.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.3-fabric",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.3-fabric-1.3.3.jar",
          "url": "handbook-26.3-fabric-1.3.3.jar",
          "size": 662675,
          "sha512": "223885448246898659989b35941853ca4c02db4b372e6acfc6b33a5b46e07548374501c35aeecf666e471f6d83e50a2bec5abfe8e8da0e0fd91d86a176ebdf72",
          "sha256": "a786a2483d41290544bc14f10117dc06b8ffce44a27e1d59657a1f06db679563",
          "sha1": "24ceabd4980d14d983b73d7e4dcaf7707ef350fe",
          "md5": "a584b0e7f78a230c088248e98a6ca612"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.3"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.3-fabric",
          "version": "1.3.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.3-fabric-1.3.3-sources.jar",
          "url": "handbook-26.3-fabric-1.3.3-sources.jar",
          "size": 440910,
          "sha512": "78591a842d67719c8f299b750c495f4fe006b034a2b99189b9d14e45e7a887afe485c4829eafb0cfa9a1d3c9a0f35160b73947c702f55dc9f9f9c7dfa5f2116a",
          "sha256": "5afa1f83aaf0c167be30e51dc8586a1dd816fb01441bb0edf0268fed018bb395",
          "sha1": "8bc46aed6509267182ad83d1b82ff990df125395",
          "md5": "5a2b583cb8cb05af9f98738349716788"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.3"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.3-fabric",
          "version": "1.3.3"
        }
      ]
    }
  ]
}
