{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-fabric",
    "version": "1.0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.1.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.1.jar",
          "size": 762658,
          "sha512": "50f0d4ac0a365a6bab6ac0834ac03928ffb4c27510d4e9f8a8f7151b42a409b412576252aa186b5466744c32b94787ab45a81336194be3f276ea9c1e1aba40db",
          "sha256": "15095559985638a1250c73f5be07daf5303eaabf09dcb2ecec59a4fda9d823c0",
          "sha1": "2ecba4d5c8bcffc68549769e8391e474f6fe145d",
          "md5": "2b313328039334243773d6eb476b7acd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.1"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "glitchcore-955399",
          "version": {
            "requires": "5660741"
          }
        },
        {
          "group": "curse.maven",
          "module": "terrablender-565956",
          "version": {
            "requires": "5864141"
          }
        },
        {
          "group": "curse.maven",
          "module": "byg-1070751",
          "version": {
            "requires": "5894945"
          }
        },
        {
          "group": "curse.maven",
          "module": "tyg-962544",
          "version": {
            "requires": "5691179"
          }
        },
        {
          "group": "curse.maven",
          "module": "corgilib-693313",
          "version": {
            "requires": "5691272"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.21.1",
          "version": {
            "requires": "4.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.1.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.1.jar",
          "size": 762658,
          "sha512": "50f0d4ac0a365a6bab6ac0834ac03928ffb4c27510d4e9f8a8f7151b42a409b412576252aa186b5466744c32b94787ab45a81336194be3f276ea9c1e1aba40db",
          "sha256": "15095559985638a1250c73f5be07daf5303eaabf09dcb2ecec59a4fda9d823c0",
          "sha1": "2ecba4d5c8bcffc68549769e8391e474f6fe145d",
          "md5": "2b313328039334243773d6eb476b7acd"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.1"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.1"
        }
      ]
    }
  ]
}
