{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-fabric",
    "version": "1.0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.1.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.1.jar",
          "size": 762659,
          "sha512": "200847f0aeaa90fd7942ff55447e028c0482b64ecba6cc0724b4a421aaf8e2bdb1e2466ab3b29d69c4bd57c435c7effedb553ab43f783e3fd7e98debed568412",
          "sha256": "1a949ec6aff69bd381aae6aeeb2bfbf681e9f63f6321b4b8df3d514381d93afe",
          "sha1": "72ade821075ad9599b0b85cca6a7f7e3e7936657",
          "md5": "475f9c93b3a0a9568bb04dfba86e068a"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.1"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.1"
        }
      ]
    }
  ]
}
