{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-common",
    "version": "1.0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.3.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.3.jar",
          "size": 133002,
          "sha512": "b6f3d8f7364b1a2d9dca220258a3f800c0b8188750c2faa936cc8c94fc1dcb582c967e32ba02a1b0f2a4c24beea5dfea986cb5410d166c99ac28f7ec2dfd01e5",
          "sha256": "59b39c93b9d0df0929883709462c5c916485124bb163e5b1be8fb585b1789e8e",
          "sha1": "afe0d9e038d6be351db47c3b43a20e1be5fc3520",
          "md5": "45f038ed7b86a88f4c474be77b954a06"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.3.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.3.jar",
          "size": 133002,
          "sha512": "b6f3d8f7364b1a2d9dca220258a3f800c0b8188750c2faa936cc8c94fc1dcb582c967e32ba02a1b0f2a4c24beea5dfea986cb5410d166c99ac28f7ec2dfd01e5",
          "sha256": "59b39c93b9d0df0929883709462c5c916485124bb163e5b1be8fb585b1789e8e",
          "sha1": "afe0d9e038d6be351db47c3b43a20e1be5fc3520",
          "md5": "45f038ed7b86a88f4c474be77b954a06"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.3"
        }
      ]
    }
  ]
}
