{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-common",
    "version": "1.0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.3.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.3.jar",
          "size": 132865,
          "sha512": "a01fcbe08ffad76e417e12c433ad04514e162e106b438f7316841949917e71e5d012a3480d28e09b991c362e7f71b47ae529cea5326b4f9060753f25c3198349",
          "sha256": "5429b8952c1e5f2ed8e5462529b12bb005e45447ec8ffc6e38da262b5d14eaba",
          "sha1": "c28447f512f3e4c18898c9cf2ffa22ef92bc0d42",
          "md5": "9c9a35d04222386c1ff9f9e5a0d35d36"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.3.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.3.jar",
          "size": 132865,
          "sha512": "a01fcbe08ffad76e417e12c433ad04514e162e106b438f7316841949917e71e5d012a3480d28e09b991c362e7f71b47ae529cea5326b4f9060753f25c3198349",
          "sha256": "5429b8952c1e5f2ed8e5462529b12bb005e45447ec8ffc6e38da262b5d14eaba",
          "sha1": "c28447f512f3e4c18898c9cf2ffa22ef92bc0d42",
          "md5": "9c9a35d04222386c1ff9f9e5a0d35d36"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.3"
        }
      ]
    }
  ]
}
