{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-26.1.2-fabric",
    "version": "2.13.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-26.1.2-fabric-2.13.0.0.jar",
          "url": "homeostatic-26.1.2-fabric-2.13.0.0.jar",
          "size": 2987573,
          "sha512": "0b69ee080da492746591067b34eec7cf7daaf87b7febaf80b9600078be6fd67e45d65159e8f24278af6fc2ba61acb63adcef80ece9bbcd450e873b905d16f5e4",
          "sha256": "020bb018b00e4a90001ee8335d77c78f94d78f3be7edcb3f6aae4b748f6231bc",
          "sha1": "cdaeb20d46bc972b57eff12e93327350fac7caed",
          "md5": "391c8301abb191a210007fe246c836da"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-26.1.2-fabric",
          "version": "2.13.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.13.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.153.0+26.1.2"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.1.2-fabric",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.2-fabric",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-26.1.2-fabric",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-26.1.2-fabric",
          "version": {
            "requires": "1.2.0.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "8.0.0-alpha.5+26.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "8.0.0-alpha.5+26.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-26.1.2-fabric-2.13.0.0.jar",
          "url": "homeostatic-26.1.2-fabric-2.13.0.0.jar",
          "size": 2987573,
          "sha512": "0b69ee080da492746591067b34eec7cf7daaf87b7febaf80b9600078be6fd67e45d65159e8f24278af6fc2ba61acb63adcef80ece9bbcd450e873b905d16f5e4",
          "sha256": "020bb018b00e4a90001ee8335d77c78f94d78f3be7edcb3f6aae4b748f6231bc",
          "sha1": "cdaeb20d46bc972b57eff12e93327350fac7caed",
          "md5": "391c8301abb191a210007fe246c836da"
        }
      ]
    }
  ]
}
