{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-common",
    "version": "2.11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.1-common-2.11.0.0.jar",
          "url": "homeostatic-1.21.1-common-2.11.0.0.jar",
          "size": 1388986,
          "sha512": "eec0d0b9b889b2b3ad835fe6bbe23963465f12e583478ffa4c622868d3b08feedd3f9c5bbb262510a9dce0277ee835e867fc92956adf17490fc4c91db7d863f7",
          "sha256": "e66bd745893e62262843bcef0b7250e1fdb9a8222315b6cd4dd611ac97baa5c1",
          "sha1": "44be8bb425c83373997e65db5bed7813ad3ff5f0",
          "md5": "2d1979921ce2c840a292644e7313575f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-common",
          "version": "2.11.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-common-2.11.0.0.jar",
          "url": "homeostatic-1.21.1-common-2.11.0.0.jar",
          "size": 1388986,
          "sha512": "eec0d0b9b889b2b3ad835fe6bbe23963465f12e583478ffa4c622868d3b08feedd3f9c5bbb262510a9dce0277ee835e867fc92956adf17490fc4c91db7d863f7",
          "sha256": "e66bd745893e62262843bcef0b7250e1fdb9a8222315b6cd4dd611ac97baa5c1",
          "sha1": "44be8bb425c83373997e65db5bed7813ad3ff5f0",
          "md5": "2d1979921ce2c840a292644e7313575f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-common",
          "version": "2.11.0.0"
        }
      ]
    }
  ]
}
