{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-fabric",
    "version": "1.21.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.5.jar",
          "url": "whitenoise-fabric-1.21.8.5.jar",
          "size": 536285,
          "sha512": "1e58193bdd3e3d976c92a4a87cc4e3f0177ffe4e8dd5b275a95096df8e04672b2905d4b68af9f7b30033fad77462540ea9b07050d118b164f848e019298976ef",
          "sha256": "09cad975a35b5024e18aec10c9aedc3f46f47f460844fb145eec1e3d822ed420",
          "sha1": "28bfc20b86de05b59cc3ca264cd73cd792a87e1d",
          "md5": "414f74e66810b682f3b0c30861b1425b"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.133.4+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.5.jar",
          "url": "whitenoise-fabric-1.21.8.5.jar",
          "size": 536285,
          "sha512": "1e58193bdd3e3d976c92a4a87cc4e3f0177ffe4e8dd5b275a95096df8e04672b2905d4b68af9f7b30033fad77462540ea9b07050d118b164f848e019298976ef",
          "sha256": "09cad975a35b5024e18aec10c9aedc3f46f47f460844fb145eec1e3d822ed420",
          "sha1": "28bfc20b86de05b59cc3ca264cd73cd792a87e1d",
          "md5": "414f74e66810b682f3b0c30861b1425b"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.5-sources.jar",
          "url": "whitenoise-fabric-1.21.8.5-sources.jar",
          "size": 71787,
          "sha512": "3e475af73c39d68f03e0a88842c7df7980fedc9895fd8b9db5b8a6fc441e4d0fd0e306d11fc459cdddc9fea34a23f4d25796d65aa625cfa56c989001a94a99ee",
          "sha256": "aa10d455e1bcaf6e6ce864e9b45c8aa804e6750a63b4618bd7d88718ce085ec1",
          "sha1": "b71b3a6912592eb3f37ad4658435b20b7b9f0f54",
          "md5": "b75b0abed80bc3d96e72b679bcb6c3df"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.5"
        }
      ]
    }
  ]
}
