{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.climatesettings",
    "module": "climatesettings-1.21.1-fabric",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "climatesettings-1.21.1-fabric-1.0.0.jar",
          "url": "climatesettings-1.21.1-fabric-1.0.0.jar",
          "size": 172055,
          "sha512": "c6b1272b30c9b233aad44949594a59d917dbee05279bd5af9d86184310da9a3f362a61e020746e8c2249401322c3a8f63a4c71451ff3b2bfd4ac28ced96feee6",
          "sha256": "f403cc8a845098271f93ef9e8027eb378d634b43585a242773ff38e752fd795d",
          "sha1": "be8cfbc8ce21bf0fa957de563db2eb1f4368ec17",
          "md5": "b6d43dcaa44cfe1fd912b91415c62728"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings",
          "version": "1.0.0"
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings-1.21.1-fabric",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "climatesettings-1.21.1-fabric-1.0.0.jar",
          "url": "climatesettings-1.21.1-fabric-1.0.0.jar",
          "size": 172055,
          "sha512": "c6b1272b30c9b233aad44949594a59d917dbee05279bd5af9d86184310da9a3f362a61e020746e8c2249401322c3a8f63a4c71451ff3b2bfd4ac28ced96feee6",
          "sha256": "f403cc8a845098271f93ef9e8027eb378d634b43585a242773ff38e752fd795d",
          "sha1": "be8cfbc8ce21bf0fa957de563db2eb1f4368ec17",
          "md5": "b6d43dcaa44cfe1fd912b91415c62728"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings",
          "version": "1.0.0"
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings-1.21.1-fabric",
          "version": "1.0.0"
        }
      ]
    }
  ]
}
