{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.11-common",
    "version": "1.1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.11-common-1.1.0.1.jar",
          "url": "homeostaticseasons-1.21.11-common-1.1.0.1.jar",
          "size": 381812,
          "sha512": "af9d709f9adf8c7692a8fd50c4a062a2d2757f1d8e2e699499cebd06a821a10dedc8fa0aa5eb984b3eb8f2f2f9bb1380f298baea88475e6180b354a037eaca5f",
          "sha256": "dfb673949624fc3a6d1252a65cdeb92e97410830f2c170e6dffa72de03eb7def",
          "sha1": "a75837c36437382051ab358c6f371b17ddc26961",
          "md5": "7c3f4d9117e064907dee900665066961"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.1.0.1"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.11-common",
          "version": "1.1.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.11-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.11-common",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.11-common-1.1.0.1.jar",
          "url": "homeostaticseasons-1.21.11-common-1.1.0.1.jar",
          "size": 381812,
          "sha512": "af9d709f9adf8c7692a8fd50c4a062a2d2757f1d8e2e699499cebd06a821a10dedc8fa0aa5eb984b3eb8f2f2f9bb1380f298baea88475e6180b354a037eaca5f",
          "sha256": "dfb673949624fc3a6d1252a65cdeb92e97410830f2c170e6dffa72de03eb7def",
          "sha1": "a75837c36437382051ab358c6f371b17ddc26961",
          "md5": "7c3f4d9117e064907dee900665066961"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.1.0.1"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.11-common",
          "version": "1.1.0.1"
        }
      ]
    }
  ]
}
