{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-fabric",
    "version": "2.11.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.9.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.9.jar",
          "size": 2965288,
          "sha512": "ad0912e684678ccac558547c265e7a67f5c636df7669c6b2ba06213ebaab38be6e7b7fb8065a1dd3f5f4e3c5e06fa400c49a73a83cb51697e88f62744544bbb7",
          "sha256": "012f21abf0b11256df9dd8da6ec9b14843665ceb437e60500e11b5f0964cc20c",
          "sha1": "b3cfbd9e8937e10157936b57ba6de5e2db3379ac",
          "md5": "397cb446d24b07f97935d3e5c945398c"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.11.0.9"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.11+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-1.21.1-fabric",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-1.21.1-fabric",
          "version": {
            "requires": "1.1.0.13"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.9.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.9.jar",
          "size": 2965288,
          "sha512": "ad0912e684678ccac558547c265e7a67f5c636df7669c6b2ba06213ebaab38be6e7b7fb8065a1dd3f5f4e3c5e06fa400c49a73a83cb51697e88f62744544bbb7",
          "sha256": "012f21abf0b11256df9dd8da6ec9b14843665ceb437e60500e11b5f0964cc20c",
          "sha1": "b3cfbd9e8937e10157936b57ba6de5e2db3379ac",
          "md5": "397cb446d24b07f97935d3e5c945398c"
        }
      ]
    }
  ]
}
