{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.10-common",
    "version": "2.11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.10-common-2.11.0.0.jar",
          "url": "homeostatic-1.21.10-common-2.11.0.0.jar",
          "size": 1619655,
          "sha512": "7c2f994bcad94ef5aa81c0947e0188e545e17f54870a5b6b8c808214b97c96323b54fe6eecc6c90fe91feaf05e65a348eb1c51d18c8724113efb2455e62c4e45",
          "sha256": "519baf0d8bac9c64a225e440839ed87b1443e665bb067603433796ad17b33f0a",
          "sha1": "8ea04ac265945e39b23ff58ff7df7a8f587abe3e",
          "md5": "c615f324086a12125f0f0358aa43af15"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.10-common",
          "version": "2.11.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.10-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.10-common",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.10-common-2.11.0.0.jar",
          "url": "homeostatic-1.21.10-common-2.11.0.0.jar",
          "size": 1619655,
          "sha512": "7c2f994bcad94ef5aa81c0947e0188e545e17f54870a5b6b8c808214b97c96323b54fe6eecc6c90fe91feaf05e65a348eb1c51d18c8724113efb2455e62c4e45",
          "sha256": "519baf0d8bac9c64a225e440839ed87b1443e665bb067603433796ad17b33f0a",
          "sha1": "8ea04ac265945e39b23ff58ff7df7a8f587abe3e",
          "md5": "c615f324086a12125f0f0358aa43af15"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.10-common",
          "version": "2.11.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.0"
        }
      ]
    }
  ]
}
