{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-common",
    "version": "1.21.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.4.jar",
          "url": "whitenoise-common-1.21.1.4.jar",
          "size": 132495,
          "sha512": "69514f2a0ef6fee7d3ca2bcf255de0a8da4fd00e1265460837dd44080741e4caa9b4f0690d9e1e412feb2f64393e65733b2432e49b64c7a661e1cdab1c3e5738",
          "sha256": "612798ba5407a623f6ded9f765b221a52bd529bd6e464f9a59fa6af815ead204",
          "sha1": "76348ea2b0b7f4cbfa524a4103b824cc2ef75541",
          "md5": "74a5604fce2647c040e800d2cdb09720"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-common-1.21.1.4.jar",
          "url": "whitenoise-common-1.21.1.4.jar",
          "size": 132495,
          "sha512": "69514f2a0ef6fee7d3ca2bcf255de0a8da4fd00e1265460837dd44080741e4caa9b4f0690d9e1e412feb2f64393e65733b2432e49b64c7a661e1cdab1c3e5738",
          "sha256": "612798ba5407a623f6ded9f765b221a52bd529bd6e464f9a59fa6af815ead204",
          "sha1": "76348ea2b0b7f4cbfa524a4103b824cc2ef75541",
          "md5": "74a5604fce2647c040e800d2cdb09720"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.4-sources.jar",
          "url": "whitenoise-common-1.21.1.4-sources.jar",
          "size": 56489,
          "sha512": "c5db91d095e46cd3360a4ecff19ee34fae6dc622751793ede0726738baf7a6c1d60c060fc1421b79eac8d4c02ba2ec06658b58af06150df96bddb808b81bc7f0",
          "sha256": "8f72694c5e1cbd98ee6ee0b764803372ed6fe64032bedac804da3f91c9bbba76",
          "sha1": "d7321c74842371075df9d971b0d5dc940916a3de",
          "md5": "12493abcffd2b26e31a91576b1e7895d"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.4"
        }
      ]
    }
  ]
}
