{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-fabric",
    "version": "2.11.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.4.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.4.jar",
          "size": 2964249,
          "sha512": "d53aeeb2ee69d4c2b73c4c2ced0a4a81660bed57224382b038c59f46fae9e8047da5839a42c0b49e812703f973b996fed2092c8370ca9c6fd9e8f6720f449fad",
          "sha256": "6ce298c1280e1d1432c9525c0e41dbdcbb36205fe7e557ccf5fe19e0088552a1",
          "sha1": "0ac8262b984018af8246de0c28d272676e685411",
          "md5": "ed1dccef74859b8d7442fa4692a9ec38"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.11.0.4"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-1.21.1-fabric",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-1.21.1-fabric",
          "version": {
            "requires": "1.1.0.4"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.4.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.4.jar",
          "size": 2964249,
          "sha512": "d53aeeb2ee69d4c2b73c4c2ced0a4a81660bed57224382b038c59f46fae9e8047da5839a42c0b49e812703f973b996fed2092c8370ca9c6fd9e8f6720f449fad",
          "sha256": "6ce298c1280e1d1432c9525c0e41dbdcbb36205fe7e557ccf5fe19e0088552a1",
          "sha1": "0ac8262b984018af8246de0c28d272676e685411",
          "md5": "ed1dccef74859b8d7442fa4692a9ec38"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.11.0.4"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.4"
        }
      ]
    }
  ]
}
