{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-1.21.9-fabric",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-fabric-2.0.0.jar",
          "url": "whitenoise-1.21.9-fabric-2.0.0.jar",
          "size": 562674,
          "sha512": "76331e10a22d8ae98e8d3ed2294c16d9ad24cd80eb4b537550d40a944e30d6000c6d18d96db12d69792583e43bdcff6ac598ef9d374468f5b9451971f69ac928",
          "sha256": "9bd31d578f204c66628e21e4e0ba46e22d480e988fc42d794dd9bb3d72fedc58",
          "sha1": "a891cf0da69bba70ce4a77eb3cef5fba96ca70da",
          "md5": "427d248637215d2f966f7e3b3550fafb"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-fabric",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.0+1.21.9"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-1.21.9-fabric-2.0.0.jar",
          "url": "whitenoise-1.21.9-fabric-2.0.0.jar",
          "size": 562674,
          "sha512": "76331e10a22d8ae98e8d3ed2294c16d9ad24cd80eb4b537550d40a944e30d6000c6d18d96db12d69792583e43bdcff6ac598ef9d374468f5b9451971f69ac928",
          "sha256": "9bd31d578f204c66628e21e4e0ba46e22d480e988fc42d794dd9bb3d72fedc58",
          "sha1": "a891cf0da69bba70ce4a77eb3cef5fba96ca70da",
          "md5": "427d248637215d2f966f7e3b3550fafb"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-fabric",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-fabric-2.0.0-sources.jar",
          "url": "whitenoise-1.21.9-fabric-2.0.0-sources.jar",
          "size": 92323,
          "sha512": "843e0db0ce9900f3de480fc32c32d10938261e2764dfb3e728acbbd8feab5232aab476023ea389baa09a1305e1b00494609f78e59b29dcd94076d541beb2191b",
          "sha256": "e6c2b49e3e414d8962b33b152def20f95a5dd542440a048cb7b35526904417cf",
          "sha1": "af43f9d6e85e4650dbd2239c826a40c081f092fd",
          "md5": "1e8809705e227a770396b0ec66ec7939"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-fabric",
          "version": "2.0.0"
        }
      ]
    }
  ]
}
