{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.1-common",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.3.jar",
          "url": "handbook-26.1.1-common-1.2.3.jar",
          "size": 622266,
          "sha512": "79bcd3efad2b6e838f62f057975f48f124ef184f2975e513db5154ebb71ce7c887b217503fb10bb782930c8a088fabd20ee40076a38f25d7dc3df3ef387cf0f2",
          "sha256": "4ef4942ab8c51b5cb30e272f5af7e7292248ea0cd2af83298ed317047a23a989",
          "sha1": "a2d8b1d1d24ae9a45008c7cef55f200a55c9f337",
          "md5": "176151a6bfc679793cbe724e14f7ef6a"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.3"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-common",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.3.jar",
          "url": "handbook-26.1.1-common-1.2.3.jar",
          "size": 622266,
          "sha512": "79bcd3efad2b6e838f62f057975f48f124ef184f2975e513db5154ebb71ce7c887b217503fb10bb782930c8a088fabd20ee40076a38f25d7dc3df3ef387cf0f2",
          "sha256": "4ef4942ab8c51b5cb30e272f5af7e7292248ea0cd2af83298ed317047a23a989",
          "sha1": "a2d8b1d1d24ae9a45008c7cef55f200a55c9f337",
          "md5": "176151a6bfc679793cbe724e14f7ef6a"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.3"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.3-sources.jar",
          "url": "handbook-26.1.1-common-1.2.3-sources.jar",
          "size": 421354,
          "sha512": "a40721eb1a0f8bd4c402352e7f9902eecf405b4ebf8d8f8861355375b1f84db205f6cdee0657938cbcc6a64407165560fd1149a02fab61a778440aa0d4531db4",
          "sha256": "eee27b36343cf2dae2daa768bf81d2ff8f79a06e91b6f5b9e89b010ffa087d7b",
          "sha1": "6111c3da6046977dd8d0fa84fe03d21177ab09bf",
          "md5": "da63e3812f31299c8196c0235ffe13a8"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.3"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.3"
        }
      ]
    }
  ]
}
