{
  "formatVersion": "1.1",
  "component": {
    "group": "guidebook",
    "module": "guidebook-1.21.1-common",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "guidebook-1.21.1-common-1.1.0.jar",
          "url": "guidebook-1.21.1-common-1.1.0.jar",
          "size": 616749,
          "sha512": "693be804d0109e91fbfa1d9ef2a3052756d53ac0372ba07053efa8ec9b2288451f455f0252ba506a8b5bbaf2979f11443470bf4adb104c0b4b3d5e87a8d6d20d",
          "sha256": "e39c7f0da81d4973803b3782eb7a2e091d19f7f779a06c131c5239164c8ef1d5",
          "sha1": "280a67777c5db0746cbc7a4127e9d01dade74637",
          "md5": "11d27938acb92aded662c0b71e9c4e12"
        }
      ],
      "capabilities": [
        {
          "group": "guidebook",
          "name": "guidebook-1.21.1-common",
          "version": "1.1.0"
        },
        {
          "group": "guidebook",
          "name": "guidebook",
          "version": "1.1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "guidebook-1.21.1-common-1.1.0.jar",
          "url": "guidebook-1.21.1-common-1.1.0.jar",
          "size": 616749,
          "sha512": "693be804d0109e91fbfa1d9ef2a3052756d53ac0372ba07053efa8ec9b2288451f455f0252ba506a8b5bbaf2979f11443470bf4adb104c0b4b3d5e87a8d6d20d",
          "sha256": "e39c7f0da81d4973803b3782eb7a2e091d19f7f779a06c131c5239164c8ef1d5",
          "sha1": "280a67777c5db0746cbc7a4127e9d01dade74637",
          "md5": "11d27938acb92aded662c0b71e9c4e12"
        }
      ],
      "capabilities": [
        {
          "group": "guidebook",
          "name": "guidebook-1.21.1-common",
          "version": "1.1.0"
        },
        {
          "group": "guidebook",
          "name": "guidebook",
          "version": "1.1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guidebook-1.21.1-common-1.1.0-sources.jar",
          "url": "guidebook-1.21.1-common-1.1.0-sources.jar",
          "size": 417901,
          "sha512": "3cb311706acdb8f2a96664fb9008d2ea29527b849e58ec46e78c416f9d298bcbe474de51d5fa55c35c08a16ae9c1cdababb1be8d4c4a491bc70af793cc13150e",
          "sha256": "d523848e69414458326af14bf0cdba6851362518d9c21ddd18370ed49026c179",
          "sha1": "03d401d177e3aaca757bb18392048ea306d6ec7d",
          "md5": "5df645a585af4743de1686c110d9118b"
        }
      ],
      "capabilities": [
        {
          "group": "guidebook",
          "name": "guidebook-1.21.1-common",
          "version": "1.1.0"
        },
        {
          "group": "guidebook",
          "name": "guidebook",
          "version": "1.1.0"
        }
      ]
    }
  ]
}
