{
  "formatVersion": "1.1",
  "component": {
    "group": "guidebook",
    "module": "guidebook-1.21.1-common",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "guidebook-1.21.1-common-1.1.0.jar",
          "url": "guidebook-1.21.1-common-1.1.0.jar",
          "size": 617096,
          "sha512": "5e1e08534fca1b33549d36c883aaa5f3389d795767dadca81d627eeb863ea7c66122b6ae7698d7975ba77286cf8f4263fe6680935b7182cd84b8eede7b680f10",
          "sha256": "b6802335f4e74c6657228a044d8ab4b2c98a3797dc33134b259d609c054f99de",
          "sha1": "e856f9617dc301b80a94c5773c836148b12d5d23",
          "md5": "3e9b99215c3116180d2b2b9c7385ba08"
        }
      ],
      "capabilities": [
        {
          "group": "guidebook",
          "name": "guidebook-1.21.1-common",
          "version": "1.1.0"
        },
        {
          "group": "guidebook",
          "name": "guidebook",
          "version": "1.1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "guidebook-1.21.1-common-1.1.0.jar",
          "url": "guidebook-1.21.1-common-1.1.0.jar",
          "size": 617096,
          "sha512": "5e1e08534fca1b33549d36c883aaa5f3389d795767dadca81d627eeb863ea7c66122b6ae7698d7975ba77286cf8f4263fe6680935b7182cd84b8eede7b680f10",
          "sha256": "b6802335f4e74c6657228a044d8ab4b2c98a3797dc33134b259d609c054f99de",
          "sha1": "e856f9617dc301b80a94c5773c836148b12d5d23",
          "md5": "3e9b99215c3116180d2b2b9c7385ba08"
        }
      ],
      "capabilities": [
        {
          "group": "guidebook",
          "name": "guidebook-1.21.1-common",
          "version": "1.1.0"
        },
        {
          "group": "guidebook",
          "name": "guidebook",
          "version": "1.1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guidebook-1.21.1-common-1.1.0-sources.jar",
          "url": "guidebook-1.21.1-common-1.1.0-sources.jar",
          "size": 418182,
          "sha512": "de841f986a5dd2e6ab5b489bcf5812364d24f85f1a9e5f0ce63f8059cbccab43279eb10ba55d0d30215505e9f6ef104dc9f425ac50ff6b16fd1494a39d81a1ba",
          "sha256": "9cbc1b466717a219d7a7d9441a175a795ad1fba3e1a29235e2f26c2a7b9fe70c",
          "sha1": "427a71f1455c492d4189a2d2b61b0d8252a24363",
          "md5": "e9334057ab0431c642a4d68a5ee22e40"
        }
      ],
      "capabilities": [
        {
          "group": "guidebook",
          "name": "guidebook-1.21.1-common",
          "version": "1.1.0"
        },
        {
          "group": "guidebook",
          "name": "guidebook",
          "version": "1.1.0"
        }
      ]
    }
  ]
}
