{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-fabric",
    "version": "1.21.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.1.4.jar",
          "url": "whitenoise-fabric-1.21.1.4.jar",
          "size": 532101,
          "sha512": "ebf57baf4ad8e449b1233d66d8905119629dfb7207b3044016f96b6c7579c608bab8f62c575f6c0e5c6486436bf9a8f7844acd74fc7ba8cc5b5ee714b6f26678",
          "sha256": "5f66c2a91c883f1f1e4de1836bed01ab1cc944cc62fe8ba010f82d51355010db",
          "sha1": "83c973d8421c4be2280b8109ca9f0fdebf00cd4e",
          "md5": "e36f9a4c19641d0033ff9aecbb40054c"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.1.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-fabric-1.21.1.4.jar",
          "url": "whitenoise-fabric-1.21.1.4.jar",
          "size": 532101,
          "sha512": "ebf57baf4ad8e449b1233d66d8905119629dfb7207b3044016f96b6c7579c608bab8f62c575f6c0e5c6486436bf9a8f7844acd74fc7ba8cc5b5ee714b6f26678",
          "sha256": "5f66c2a91c883f1f1e4de1836bed01ab1cc944cc62fe8ba010f82d51355010db",
          "sha1": "83c973d8421c4be2280b8109ca9f0fdebf00cd4e",
          "md5": "e36f9a4c19641d0033ff9aecbb40054c"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.1.4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.1.4-sources.jar",
          "url": "whitenoise-fabric-1.21.1.4-sources.jar",
          "size": 70253,
          "sha512": "c5f96ce0b5458873609ae4e1d26437948127f47bb6f9bfb844f80b3c505d00de168f0787d41d880daf68786d3a3209a1a6f62797fd0244ae16938fb9b0cfdd33",
          "sha256": "c61d35c91251284a21fa83d6bf041e65b1d20fb3a73582e3e142f1c339fe1c18",
          "sha1": "756db72bebbf5c66339f3ff19d1789e86eae79c4",
          "md5": "e78b285bf259dcf3f9d5739fb7d3185f"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.4"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.1.4"
        }
      ]
    }
  ]
}
