{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.1-fabric",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.2.jar",
          "url": "handbook-26.1.1-fabric-1.2.2.jar",
          "size": 652593,
          "sha512": "1116ee86c7a230bdeabebed3a92fd5d4ed6121c87bc8eb770037adf0ea357d36be79ddd9d91175629ca0c305c5655d92f6aed536577c4bf421e609991561b30f",
          "sha256": "c7a3363617b4e17c74a1afed9c82a81d9c706bfd7814691b2499ee777effcc35",
          "sha1": "8ca9c669dd8d31b2db0e9c21a3aa84408413616a",
          "md5": "743971fd21c0dd35f820261d433cb884"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.2+26.1.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "18.0.0-alpha.8"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.2.jar",
          "url": "handbook-26.1.1-fabric-1.2.2.jar",
          "size": 652593,
          "sha512": "1116ee86c7a230bdeabebed3a92fd5d4ed6121c87bc8eb770037adf0ea357d36be79ddd9d91175629ca0c305c5655d92f6aed536577c4bf421e609991561b30f",
          "sha256": "c7a3363617b4e17c74a1afed9c82a81d9c706bfd7814691b2499ee777effcc35",
          "sha1": "8ca9c669dd8d31b2db0e9c21a3aa84408413616a",
          "md5": "743971fd21c0dd35f820261d433cb884"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.2-sources.jar",
          "url": "handbook-26.1.1-fabric-1.2.2-sources.jar",
          "size": 435676,
          "sha512": "f371a9da11c3387828f2f8196b6d1f4f31f4a49568e56a882c479f374aed3b1cb58cd2059ffc87012d1885c94ecf4ff32b00e54459655fb87a53833439615cfa",
          "sha256": "b46ac4c734c6f612030ba9ffb179fd94b49e64235e84a6a00d0f5a3af653ed09",
          "sha1": "b1cfe1bb9a91102bfcf82c000e71e6fd29796f5a",
          "md5": "897c16434b4fcd9bbbe2a332a1fc03fd"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.2"
        }
      ]
    }
  ]
}
