{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.1-fabric",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.2.jar",
          "url": "handbook-26.1.1-fabric-1.2.2.jar",
          "size": 650197,
          "sha512": "c7a44a66b3b91bc4792b51ee9e9b74db2b52ca554c28f6606e702591f578921bfa8fd28f5953c970a4ef02fcbf55d56e5c8755758b13c91cac880a9889965837",
          "sha256": "4ce691c798398d687233abbfa8e096994bcd44c9ad1792d0540d635d9f90c0ed",
          "sha1": "3e8d4f4ff79e3d7fb03660bdd52838ff5adfec8a",
          "md5": "ea275f41525f09f17b28f436057b692f"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.2+26.1.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "18.0.0-alpha.8"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.2.jar",
          "url": "handbook-26.1.1-fabric-1.2.2.jar",
          "size": 650197,
          "sha512": "c7a44a66b3b91bc4792b51ee9e9b74db2b52ca554c28f6606e702591f578921bfa8fd28f5953c970a4ef02fcbf55d56e5c8755758b13c91cac880a9889965837",
          "sha256": "4ce691c798398d687233abbfa8e096994bcd44c9ad1792d0540d635d9f90c0ed",
          "sha1": "3e8d4f4ff79e3d7fb03660bdd52838ff5adfec8a",
          "md5": "ea275f41525f09f17b28f436057b692f"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.2-sources.jar",
          "url": "handbook-26.1.1-fabric-1.2.2-sources.jar",
          "size": 435746,
          "sha512": "606746334d6e891332a4cb894a9d287258b7ded5462261d27e0749666fa925e7405006b195265211d849a326b1430691f8f2dc8713dfc2c4656c178853963c29",
          "sha256": "5e22c5c4dea812b48cf3cbb65607a0ba0332261f253e1e39d40d8625c384a7bb",
          "sha1": "bdad8ce748ba77397ffc3902a8898087f2f794b7",
          "md5": "83ad4a57e4642eda47d24d30b72e2404"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.2"
        }
      ]
    }
  ]
}
