{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.1-fabric",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.2.jar",
          "url": "handbook-26.1.1-fabric-1.2.2.jar",
          "size": 650197,
          "sha512": "d9a618682141b4f0c0caa0c5bab30b46d440b7ac2dbbb0b18b04ce35178aaa1db53c1a06fe3e0e70e58bf3949ee794e39f7f24374a4d060e00f708045693a92f",
          "sha256": "6268a6705ab2e54099bad8512458d2fa6f4f1acf2fa25098f6f1c5182ca764ec",
          "sha1": "2ded284404c36f4a032887e87ffc8400db84eb13",
          "md5": "7d98ce3a2ef20c71610dc85ea2ce59ef"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.2+26.1.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "18.0.0-alpha.8"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.2.jar",
          "url": "handbook-26.1.1-fabric-1.2.2.jar",
          "size": 650197,
          "sha512": "d9a618682141b4f0c0caa0c5bab30b46d440b7ac2dbbb0b18b04ce35178aaa1db53c1a06fe3e0e70e58bf3949ee794e39f7f24374a4d060e00f708045693a92f",
          "sha256": "6268a6705ab2e54099bad8512458d2fa6f4f1acf2fa25098f6f1c5182ca764ec",
          "sha1": "2ded284404c36f4a032887e87ffc8400db84eb13",
          "md5": "7d98ce3a2ef20c71610dc85ea2ce59ef"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.1-fabric-1.2.2-sources.jar",
          "url": "handbook-26.1.1-fabric-1.2.2-sources.jar",
          "size": 435746,
          "sha512": "606746334d6e891332a4cb894a9d287258b7ded5462261d27e0749666fa925e7405006b195265211d849a326b1430691f8f2dc8713dfc2c4656c178853963c29",
          "sha256": "5e22c5c4dea812b48cf3cbb65607a0ba0332261f253e1e39d40d8625c384a7bb",
          "sha1": "bdad8ce748ba77397ffc3902a8898087f2f794b7",
          "md5": "83ad4a57e4642eda47d24d30b72e2404"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-fabric",
          "version": "1.2.2"
        }
      ]
    }
  ]
}
