{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-1.21.9-common",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-common-2.0.0.jar",
          "url": "whitenoise-1.21.9-common-2.0.0.jar",
          "size": 161272,
          "sha512": "b6e284241291779068fbf6cbf2480e0efda2057884d88e2080d63a81c4dc5e198519c904d49b7b7ba6d0be6b2215ec00ad78fec928f196d4c5fce9ec4fcd9420",
          "sha256": "c46829f26eff0ded61945ecd79d986c6e7e86eae92ea8bc3277f1b8eb7600088",
          "sha1": "325fc7203afad03fb32b56b6777a187bc31c64a4",
          "md5": "0e9648f6610bac4a5d2d51e608dfe58d"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-common",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-1.21.9-common-2.0.0.jar",
          "url": "whitenoise-1.21.9-common-2.0.0.jar",
          "size": 161272,
          "sha512": "b6e284241291779068fbf6cbf2480e0efda2057884d88e2080d63a81c4dc5e198519c904d49b7b7ba6d0be6b2215ec00ad78fec928f196d4c5fce9ec4fcd9420",
          "sha256": "c46829f26eff0ded61945ecd79d986c6e7e86eae92ea8bc3277f1b8eb7600088",
          "sha1": "325fc7203afad03fb32b56b6777a187bc31c64a4",
          "md5": "0e9648f6610bac4a5d2d51e608dfe58d"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-common",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-1.21.9-common-2.0.0-sources.jar",
          "url": "whitenoise-1.21.9-common-2.0.0-sources.jar",
          "size": 76953,
          "sha512": "4ebf64b4a730fbc12f34a5ab7f0c196b00cf912dce6f0e47a7f57426b00b4485db428210646ceb6729348a3b91ebf54e6df66bde2ac8901a8063c576091c7026",
          "sha256": "44b70a801bbc9eaf5038eff77d2fbaceac3ae2f975bb8a634be2c6bb74209be7",
          "sha1": "2bc1ed26eca65ddf89e37c41b76c252a8059782b",
          "md5": "bf8ff4c145a801ab1c2281271b08d314"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.9-common",
          "version": "2.0.0"
        }
      ]
    }
  ]
}
