{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-26.1.2-common",
    "version": "2.11.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-26.1.2-common-2.11.0.9.jar",
          "url": "homeostatic-26.1.2-common-2.11.0.9.jar",
          "size": 1563548,
          "sha512": "eaeae9275fc13faf77a9c9277a3d6b21be6d2301a6a5effad5a11bed9a0bf2ed2c0b9f64309571b2fe18c409399d9f0c1dc9c148688d582541a5dd7d7a40f213",
          "sha256": "1bee10df9aac68ea937b4008ebecf25594dde1b5abe31c5a0e98cccd7e5d8193",
          "sha1": "ae0bc80890757db537b79eabe25488adef7dc9b3",
          "md5": "12b46acafee2ce18b5bc8246f54fc0af"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-26.1.2-common",
          "version": "2.11.0.9"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.2-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.1.2-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-26.1.2-common",
          "version": {
            "requires": "1.1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-26.1.2-common-2.11.0.9.jar",
          "url": "homeostatic-26.1.2-common-2.11.0.9.jar",
          "size": 1563548,
          "sha512": "eaeae9275fc13faf77a9c9277a3d6b21be6d2301a6a5effad5a11bed9a0bf2ed2c0b9f64309571b2fe18c409399d9f0c1dc9c148688d582541a5dd7d7a40f213",
          "sha256": "1bee10df9aac68ea937b4008ebecf25594dde1b5abe31c5a0e98cccd7e5d8193",
          "sha1": "ae0bc80890757db537b79eabe25488adef7dc9b3",
          "md5": "12b46acafee2ce18b5bc8246f54fc0af"
        }
      ]
    }
  ]
}
