{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-common",
    "version": "1.0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.2.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.2.jar",
          "size": 132864,
          "sha512": "184b5e82b5f060f21facb91b88c585797faebe572ee68560a633888f31ed7df2c9a716dcb5fe5f5bcc4e9dfc980d92bf42fb6dde0303c75964d2b55b8ec6edef",
          "sha256": "1de0ccf9bfc6cbc3b2fa20c2c28ac5b14d665adcf68cc1ddf116b48f64179b1c",
          "sha1": "20f9893bf51f4883b0e9d01052ca13e402127e17",
          "md5": "34da8bfc69a8f7e8f9742f5efae242a6"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.2"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.2.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.2.jar",
          "size": 132864,
          "sha512": "184b5e82b5f060f21facb91b88c585797faebe572ee68560a633888f31ed7df2c9a716dcb5fe5f5bcc4e9dfc980d92bf42fb6dde0303c75964d2b55b8ec6edef",
          "sha256": "1de0ccf9bfc6cbc3b2fa20c2c28ac5b14d665adcf68cc1ddf116b48f64179b1c",
          "sha1": "20f9893bf51f4883b0e9d01052ca13e402127e17",
          "md5": "34da8bfc69a8f7e8f9742f5efae242a6"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.2"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.2"
        }
      ]
    }
  ]
}
