{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-common",
    "version": "1.0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.2.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.2.jar",
          "size": 132864,
          "sha512": "545fc325a3c6c2c42790638dd71fe5bc5b7d8179f0e249448c9219a3653e768483ee08da26c71b2d02ef5e814012f84e4ac081e8cbbe30af1a71bbc152fdae1a",
          "sha256": "604ab978956d858cd00f4650713bbe2f809bec373ac5039ee2a43bbcc2378c01",
          "sha1": "8b972fd40eb82b5199e3e89515c7951c1e316e79",
          "md5": "f968072d4cb1104714456d2843d76825"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.2"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.2.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.2.jar",
          "size": 132864,
          "sha512": "545fc325a3c6c2c42790638dd71fe5bc5b7d8179f0e249448c9219a3653e768483ee08da26c71b2d02ef5e814012f84e4ac081e8cbbe30af1a71bbc152fdae1a",
          "sha256": "604ab978956d858cd00f4650713bbe2f809bec373ac5039ee2a43bbcc2378c01",
          "sha1": "8b972fd40eb82b5199e3e89515c7951c1e316e79",
          "md5": "f968072d4cb1104714456d2843d76825"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.2"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.2"
        }
      ]
    }
  ]
}
