{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.climatesettings",
    "module": "climatesettings-1.21.1-common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "climatesettings-1.21.1-common-1.0.0.jar",
          "url": "climatesettings-1.21.1-common-1.0.0.jar",
          "size": 173361,
          "sha512": "1d688464fcb552b1585b65f82faba3f106b917fa55e31bc250005df4a9ddab95acd48482919f3fa2dae14ac89068af4252ec5c47acfd7eea066cca9c1892feb6",
          "sha256": "b539b2aa94cfe85efac345cadc236ca59d55718bcc2d945cbb5bca304b1c2c60",
          "sha1": "e92e7a377e15cacf88b6dc366bbe3cf5421ef4b8",
          "md5": "da69c43c37b1efd92e5bcc26ec2efd08"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings",
          "version": "1.0.0"
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings-1.21.1-common",
          "version": "1.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "climatesettings-1.21.1-common-1.0.0.jar",
          "url": "climatesettings-1.21.1-common-1.0.0.jar",
          "size": 173361,
          "sha512": "1d688464fcb552b1585b65f82faba3f106b917fa55e31bc250005df4a9ddab95acd48482919f3fa2dae14ac89068af4252ec5c47acfd7eea066cca9c1892feb6",
          "sha256": "b539b2aa94cfe85efac345cadc236ca59d55718bcc2d945cbb5bca304b1c2c60",
          "sha1": "e92e7a377e15cacf88b6dc366bbe3cf5421ef4b8",
          "md5": "da69c43c37b1efd92e5bcc26ec2efd08"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings",
          "version": "1.0.0"
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "name": "climatesettings-1.21.1-common",
          "version": "1.0.0"
        }
      ]
    }
  ]
}
