{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-common",
    "version": "1.21.1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.17.jar",
          "url": "whitenoise-common-1.21.1.17.jar",
          "size": 132966,
          "sha512": "de31fd88e32d562cb763bd61ceea6ca1b5480a8995bf6b87ab5fea9abf19a3c52ea28943d03fdac3a3826fcb151951f606913dfa8166985d88a929a265360ecb",
          "sha256": "6eeaa363f6c595163b5a6e1f735c72f5fb159e2fc75148fe598b2067ccbc4993",
          "sha1": "d4f005f70632397e89dfc6e991c530dc77e42149",
          "md5": "1414ccea2f336adf097c4b5c0cd4e42a"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.17"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-common-1.21.1.17.jar",
          "url": "whitenoise-common-1.21.1.17.jar",
          "size": 132966,
          "sha512": "de31fd88e32d562cb763bd61ceea6ca1b5480a8995bf6b87ab5fea9abf19a3c52ea28943d03fdac3a3826fcb151951f606913dfa8166985d88a929a265360ecb",
          "sha256": "6eeaa363f6c595163b5a6e1f735c72f5fb159e2fc75148fe598b2067ccbc4993",
          "sha1": "d4f005f70632397e89dfc6e991c530dc77e42149",
          "md5": "1414ccea2f336adf097c4b5c0cd4e42a"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.17"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.17-sources.jar",
          "url": "whitenoise-common-1.21.1.17-sources.jar",
          "size": 56685,
          "sha512": "12f7c4c4df92063853f93e7e7f2352a6a01f11ca461e84bdf3fe09e75528030fb37bc9674db6d89c1f783ed2aa0b6989d3edcdc9ba95e05959dff0be61380cae",
          "sha256": "1477a4761353b9a88408bd89b3d19f2fb210cc4b87447b5bc5b8767790b817bc",
          "sha1": "24066ec301b3076ae7bddf8a9245d8ed1bcfad14",
          "md5": "2f903df7a7c60c3194326979c46256cc"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.17"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.17"
        }
      ]
    }
  ]
}
