{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.guidebook",
    "module": "guidebook-1.21.1-fabric",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "guidebook-1.21.1-fabric-1.1.1.jar",
          "url": "guidebook-1.21.1-fabric-1.1.1.jar",
          "size": 652736,
          "sha512": "cf07d3f420cb55edd3172ba37ccdf4c33068927aef326962a80b0cb6761224e2e213233f4de1014098fe06799c49b809f10f15b2e03252b6cbbbd73ee1222d4d",
          "sha256": "c4789213b758cc0241adb2892283cb4ac977f435b42d8ad80849dcf17f95a499",
          "sha1": "0ea02fe1559c5ca2d5a7f3ec324ecc9beaccd428",
          "md5": "9fbe9cc8ab646e3dfbc8292149f001a1"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook",
          "version": "1.1.1"
        },
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook-1.21.1-fabric",
          "version": "1.1.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.799"
          }
        }
      ],
      "files": [
        {
          "name": "guidebook-1.21.1-fabric-1.1.1.jar",
          "url": "guidebook-1.21.1-fabric-1.1.1.jar",
          "size": 652736,
          "sha512": "cf07d3f420cb55edd3172ba37ccdf4c33068927aef326962a80b0cb6761224e2e213233f4de1014098fe06799c49b809f10f15b2e03252b6cbbbd73ee1222d4d",
          "sha256": "c4789213b758cc0241adb2892283cb4ac977f435b42d8ad80849dcf17f95a499",
          "sha1": "0ea02fe1559c5ca2d5a7f3ec324ecc9beaccd428",
          "md5": "9fbe9cc8ab646e3dfbc8292149f001a1"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook",
          "version": "1.1.1"
        },
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook-1.21.1-fabric",
          "version": "1.1.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guidebook-1.21.1-fabric-1.1.1-sources.jar",
          "url": "guidebook-1.21.1-fabric-1.1.1-sources.jar",
          "size": 442804,
          "sha512": "600c7937af0b964e49a479c4667b058af535890a201abaa335a136055dccdd4a9d433c7679cc361f39f5d1a7351a53ded2d694602781effa61864da1bf974ea5",
          "sha256": "e7225a40dce014e12843bbbe4c8225df0f5a8294f59b30b801079cfdedfa7006",
          "sha1": "9fe6d2d1b2d7d05f3c87f4aded0e6a525f43c036",
          "md5": "27191d1fc5af190398c0e17f39f265da"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook",
          "version": "1.1.1"
        },
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook-1.21.1-fabric",
          "version": "1.1.1"
        }
      ]
    }
  ]
}
