{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-fabric",
    "version": "2.11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.0.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.0.jar",
          "size": 2739465,
          "sha512": "b65bab2bfdedb2b70f276785623f9df610e124b74f5fce617d8d2edf374f084e03091686a641e687e8fe229ac69ecabd0dc41a054ea9427913c7af032ebd307d",
          "sha256": "a1d6a6195dcdab0af3e37110321d13773784577c2f5e5b1304ace8da8b21b4df",
          "sha1": "c6e6a179fcb3b3e91fbfc9c462708764f1e3aee0",
          "md5": "dab2e62e5c59adaf3be6291c6aa79737"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.11.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-1.21.1-fabric",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.799"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "terrablender-565956",
          "version": {
            "requires": "5864141"
          }
        },
        {
          "group": "curse.maven",
          "module": "byg-1070751",
          "version": {
            "requires": "5894945"
          }
        },
        {
          "group": "curse.maven",
          "module": "tyg-962544",
          "version": {
            "requires": "5691179"
          }
        },
        {
          "group": "curse.maven",
          "module": "corgilib-693313",
          "version": {
            "requires": "5691272"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.21.1",
          "version": {
            "requires": "4.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.0.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.0.jar",
          "size": 2739465,
          "sha512": "b65bab2bfdedb2b70f276785623f9df610e124b74f5fce617d8d2edf374f084e03091686a641e687e8fe229ac69ecabd0dc41a054ea9427913c7af032ebd307d",
          "sha256": "a1d6a6195dcdab0af3e37110321d13773784577c2f5e5b1304ace8da8b21b4df",
          "sha1": "c6e6a179fcb3b3e91fbfc9c462708764f1e3aee0",
          "md5": "dab2e62e5c59adaf3be6291c6aa79737"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.11.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.0"
        }
      ]
    }
  ]
}
