{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-26.1.2-fabric",
    "version": "2.11.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-26.1.2-fabric-2.11.0.4.jar",
          "url": "homeostatic-26.1.2-fabric-2.11.0.4.jar",
          "size": 2966599,
          "sha512": "69686b6a40bd86fab1488b90903e706e729a822e8533c533bfa32ca81b91726103f942ad0d1af16324f3ba1b6566204197310ed58e6acc4ad70f27db9f8c8345",
          "sha256": "28a0ee0abd7004ab372184a30073e0f44c8d4e5af47d811c1ddb7a8da251e7d1",
          "sha1": "18a8dd254804eb88bdb8b0090a30f56801ef940b",
          "md5": "9fd3a05c6f398ea4170f2e07f6c4846e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-26.1.2-fabric",
          "version": "2.11.0.4"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.2"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.1.2-fabric",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.2-fabric",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-26.1.2-fabric",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-26.1.2-fabric",
          "version": {
            "requires": "1.1.0.7"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "8.0.0-alpha.5+26.1"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "8.0.0-alpha.5+26.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-26.1.2-fabric-2.11.0.4.jar",
          "url": "homeostatic-26.1.2-fabric-2.11.0.4.jar",
          "size": 2966599,
          "sha512": "69686b6a40bd86fab1488b90903e706e729a822e8533c533bfa32ca81b91726103f942ad0d1af16324f3ba1b6566204197310ed58e6acc4ad70f27db9f8c8345",
          "sha256": "28a0ee0abd7004ab372184a30073e0f44c8d4e5af47d811c1ddb7a8da251e7d1",
          "sha1": "18a8dd254804eb88bdb8b0090a30f56801ef940b",
          "md5": "9fd3a05c6f398ea4170f2e07f6c4846e"
        }
      ]
    }
  ]
}
