{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-26.3-common",
    "version": "1.2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-26.3-common-1.2.0.3.jar",
          "url": "homeostaticseasons-26.3-common-1.2.0.3.jar",
          "size": 387784,
          "sha512": "d88f27dd944612e40da5f0bdc83f9663977ea59b3a282872e8a27258191b15d60664a939ac720c1eb6bd9e92960abd0cbff1d670dbc4d5e916a6d20a515f54bc",
          "sha256": "3b5885c6bd276ae9d8bc733fae968cdb4ca2c20b566a0c064b956e0db3a2d48a",
          "sha1": "c0fb991d1711fa8e138278ccd8fb62095cba0996",
          "md5": "a13552eca231b71d20f67c3aa8c42c33"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-26.3-common",
          "version": "1.2.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.2.0.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.3-common",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.3-common",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-26.3-common-1.2.0.3.jar",
          "url": "homeostaticseasons-26.3-common-1.2.0.3.jar",
          "size": 387784,
          "sha512": "d88f27dd944612e40da5f0bdc83f9663977ea59b3a282872e8a27258191b15d60664a939ac720c1eb6bd9e92960abd0cbff1d670dbc4d5e916a6d20a515f54bc",
          "sha256": "3b5885c6bd276ae9d8bc733fae968cdb4ca2c20b566a0c064b956e0db3a2d48a",
          "sha1": "c0fb991d1711fa8e138278ccd8fb62095cba0996",
          "md5": "a13552eca231b71d20f67c3aa8c42c33"
        }
      ]
    }
  ]
}
