{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-26.3-fabric",
    "version": "1.2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-26.3-fabric-1.2.0.4.jar",
          "url": "homeostaticseasons-26.3-fabric-1.2.0.4.jar",
          "size": 1024281,
          "sha512": "7227231fa58f9035d2ef221f2da73cf52c15b253293984851406bdd707e5a54d9aedbafc5f25103ce4cbd5a78bb9d981b3cb918f1bd5ad336def204300e6358a",
          "sha256": "e04bf4ff68bb97811fd6640d49d2252aacaa91933e4d73b3934548f4e13e0026",
          "sha1": "32933c8076b369878756b5784e6c3b5566d20c25",
          "md5": "fdd3a919f15f9a79df6fc90ed5f47771"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.2.0.4"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-26.3-fabric",
          "version": "1.2.0.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.3-fabric",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.3-fabric",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-26.3-fabric-1.2.0.4.jar",
          "url": "homeostaticseasons-26.3-fabric-1.2.0.4.jar",
          "size": 1024281,
          "sha512": "7227231fa58f9035d2ef221f2da73cf52c15b253293984851406bdd707e5a54d9aedbafc5f25103ce4cbd5a78bb9d981b3cb918f1bd5ad336def204300e6358a",
          "sha256": "e04bf4ff68bb97811fd6640d49d2252aacaa91933e4d73b3934548f4e13e0026",
          "sha1": "32933c8076b369878756b5784e6c3b5566d20c25",
          "md5": "fdd3a919f15f9a79df6fc90ed5f47771"
        }
      ]
    }
  ]
}
