{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.10-fabric",
    "version": "2.11.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.10-fabric-2.11.0.0.jar",
          "url": "homeostatic-1.21.10-fabric-2.11.0.0.jar",
          "size": 2977343,
          "sha512": "173b9a51e9c0c9d70f50711e54a8ac1a94062598406d8c011635f658c956dc659b11b9be067981334a9290a0979395600e561d41fbcfd8c29b76ea0ef9ddae73",
          "sha256": "07e1e6fdc513d5b8eb2ca3905c462a6aba001f20669b4a3a6b80a28be839a65e",
          "sha1": "52f72aeaef7a67777dc051b39df55b7012b1a1f6",
          "md5": "cce19420c724fb5558edc4d2eb451f3f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.10-fabric",
          "version": "2.11.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.3+1.21.10"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.10-fabric",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.10-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-1.21.10-fabric",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.10-fabric-2.11.0.0.jar",
          "url": "homeostatic-1.21.10-fabric-2.11.0.0.jar",
          "size": 2977343,
          "sha512": "173b9a51e9c0c9d70f50711e54a8ac1a94062598406d8c011635f658c956dc659b11b9be067981334a9290a0979395600e561d41fbcfd8c29b76ea0ef9ddae73",
          "sha256": "07e1e6fdc513d5b8eb2ca3905c462a6aba001f20669b4a3a6b80a28be839a65e",
          "sha1": "52f72aeaef7a67777dc051b39df55b7012b1a1f6",
          "md5": "cce19420c724fb5558edc4d2eb451f3f"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.10-fabric",
          "version": "2.11.0.0"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.0"
        }
      ]
    }
  ]
}
