{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-common",
    "version": "1.21.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.5.jar",
          "url": "whitenoise-common-1.21.1.5.jar",
          "size": 132494,
          "sha512": "ae0115fc647ce64eabe866f6b7497797b7a5ef1b9b2b0f777ba9a309790b6461668c06c48b4172121a853971e99a40ad7c8165b16188c087a41d9bdee427947c",
          "sha256": "ce84fd8c393cd8a2b0a3160b9faf10cb6c987be4f3e9b30c1a2019b4938823f0",
          "sha1": "937b04f629198b37de6ddfae4760564b3bb9ddb7",
          "md5": "038bb0a0c203ea73bc3fce5d9b1e4d99"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-common-1.21.1.5.jar",
          "url": "whitenoise-common-1.21.1.5.jar",
          "size": 132494,
          "sha512": "ae0115fc647ce64eabe866f6b7497797b7a5ef1b9b2b0f777ba9a309790b6461668c06c48b4172121a853971e99a40ad7c8165b16188c087a41d9bdee427947c",
          "sha256": "ce84fd8c393cd8a2b0a3160b9faf10cb6c987be4f3e9b30c1a2019b4938823f0",
          "sha1": "937b04f629198b37de6ddfae4760564b3bb9ddb7",
          "md5": "038bb0a0c203ea73bc3fce5d9b1e4d99"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.5-sources.jar",
          "url": "whitenoise-common-1.21.1.5-sources.jar",
          "size": 56489,
          "sha512": "1f80baee12068a312fdff869830b5f51869ab2accac5bd74dbd406a3126839c7449fc2dbe74d17c542b4a4b04987f8d2f75e5e638f58a4430bb4c1d2267d41c9",
          "sha256": "902008d5b477e9b398aa0beeb7880f31df871deb79eae0c7eecfbe99e4c25e66",
          "sha1": "825f39558ec4c1e164b6d94b68995c4fe6e25c48",
          "md5": "4f7b2c3f9f5caa39b02b6db0c649e399"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.5"
        }
      ]
    }
  ]
}
