{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-fabric",
    "version": "1.0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.3.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.3.jar",
          "size": 762660,
          "sha512": "34924f8ec2e1e44d03a1de3c1fbf804058e6edfb934ef65139d7a6553b67ed16c031ad1c18c2fdf25b705534b1fc67094817e90822fa845124dff2712f58bcd2",
          "sha256": "8befeb9c11a973019258acf038df567b4b53b703ffd382d6ae798a7145ac0c72",
          "sha1": "fe0c1673417557d72fe2ccd568151ada8811e88e",
          "md5": "4d88f78787e3cc471b8fb2739c3ae179"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.3.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.3.jar",
          "size": 762660,
          "sha512": "34924f8ec2e1e44d03a1de3c1fbf804058e6edfb934ef65139d7a6553b67ed16c031ad1c18c2fdf25b705534b1fc67094817e90822fa845124dff2712f58bcd2",
          "sha256": "8befeb9c11a973019258acf038df567b4b53b703ffd382d6ae798a7145ac0c72",
          "sha1": "fe0c1673417557d72fe2ccd568151ada8811e88e",
          "md5": "4d88f78787e3cc471b8fb2739c3ae179"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.3"
        }
      ]
    }
  ]
}
