{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-fabric",
    "version": "1.0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.3.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.3.jar",
          "size": 762818,
          "sha512": "8bf8425ab88d70aaeaacf9d245215472d56bad77ec11af451f00540235827fdb54ab68fe63bf4079339197b32d093d62a211052d9c70f499d0ff0c663c1389f6",
          "sha256": "bc08a3082bd2b9aa5a450c93a8c0d768e3863579ebbc937ec28962152907b835",
          "sha1": "ed34d25b3951190cd745c283f7045aff55ed2325",
          "md5": "fe8fb2c3e10e0ad429d26dd04d9f3972"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.3.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.3.jar",
          "size": 762818,
          "sha512": "8bf8425ab88d70aaeaacf9d245215472d56bad77ec11af451f00540235827fdb54ab68fe63bf4079339197b32d093d62a211052d9c70f499d0ff0c663c1389f6",
          "sha256": "bc08a3082bd2b9aa5a450c93a8c0d768e3863579ebbc937ec28962152907b835",
          "sha1": "ed34d25b3951190cd745c283f7045aff55ed2325",
          "md5": "fe8fb2c3e10e0ad429d26dd04d9f3972"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.3"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.3"
        }
      ]
    }
  ]
}
