{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.1-common",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.2.jar",
          "url": "handbook-26.1.1-common-1.2.2.jar",
          "size": 619889,
          "sha512": "16fca56df428f7137a29a427d01d5fc9b4e6e28436d89b04782b0d465ed325fe4165eebfa9d3ea2200373183af2af80c5528512c17cb1f7794318de28309d186",
          "sha256": "e7ac9f245679e5e4e59c7d55539b305d5d99878f61e1561397e2e920778b7932",
          "sha1": "1a69b9d4543e1bfd4b754200b7bd9a13fc02c616",
          "md5": "fda40afaed50007127a552dcf337aa98"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-common",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.2.jar",
          "url": "handbook-26.1.1-common-1.2.2.jar",
          "size": 619889,
          "sha512": "16fca56df428f7137a29a427d01d5fc9b4e6e28436d89b04782b0d465ed325fe4165eebfa9d3ea2200373183af2af80c5528512c17cb1f7794318de28309d186",
          "sha256": "e7ac9f245679e5e4e59c7d55539b305d5d99878f61e1561397e2e920778b7932",
          "sha1": "1a69b9d4543e1bfd4b754200b7bd9a13fc02c616",
          "md5": "fda40afaed50007127a552dcf337aa98"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.2-sources.jar",
          "url": "handbook-26.1.1-common-1.2.2-sources.jar",
          "size": 421424,
          "sha512": "4e125f45e7fd4b6f2c5ace981bedce558308214dcfa6566a3d44008c6ce8aebb5707092e1fd376d720d669f2c5f2a8cf673697051b4839652d679dc4d3b5ee4a",
          "sha256": "80f137d8c0a13ceffd6d02bb771868f48ff44db30d99e5765128a470b5f318a7",
          "sha1": "435c27ea295dd58abb1f9e7b3ec733454c841e28",
          "md5": "947dc8104efd48a2b6bb05a13bff65dc"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.2"
        }
      ]
    }
  ]
}
