{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.1-common",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.2.jar",
          "url": "handbook-26.1.1-common-1.2.2.jar",
          "size": 619890,
          "sha512": "e07e6969296734f56ee51fa7de87a722f5ba5e7c5670307891e0378ad9c95e6514ef7188e31026842fe6548db5778143480defe78aaf66ca273a35454571bad3",
          "sha256": "5e9c8b1172cde070dcedca257cac1b1b7f9a686451f43b1d5961b81c8739a092",
          "sha1": "f3f0c943955f6e7f101fbe93474d9fdad12f913e",
          "md5": "255d5b6bcd38fc2633eeba2c6ee15ec7"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-common",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.2.jar",
          "url": "handbook-26.1.1-common-1.2.2.jar",
          "size": 619890,
          "sha512": "e07e6969296734f56ee51fa7de87a722f5ba5e7c5670307891e0378ad9c95e6514ef7188e31026842fe6548db5778143480defe78aaf66ca273a35454571bad3",
          "sha256": "5e9c8b1172cde070dcedca257cac1b1b7f9a686451f43b1d5961b81c8739a092",
          "sha1": "f3f0c943955f6e7f101fbe93474d9fdad12f913e",
          "md5": "255d5b6bcd38fc2633eeba2c6ee15ec7"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.2-sources.jar",
          "url": "handbook-26.1.1-common-1.2.2-sources.jar",
          "size": 421424,
          "sha512": "4e125f45e7fd4b6f2c5ace981bedce558308214dcfa6566a3d44008c6ce8aebb5707092e1fd376d720d669f2c5f2a8cf673697051b4839652d679dc4d3b5ee4a",
          "sha256": "80f137d8c0a13ceffd6d02bb771868f48ff44db30d99e5765128a470b5f318a7",
          "sha1": "435c27ea295dd58abb1f9e7b3ec733454c841e28",
          "md5": "947dc8104efd48a2b6bb05a13bff65dc"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.2"
        }
      ]
    }
  ]
}
