{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.1-common",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.2.jar",
          "url": "handbook-26.1.1-common-1.2.2.jar",
          "size": 622267,
          "sha512": "39989f119320886942051038402064e76576e2b4f27847e86612c2ff6a50d98ba8b50fd18a22e356c83230e871d7f8e9c671ea8c73736bc30d0c9a4466024279",
          "sha256": "d2b5a2de39864b86b97d0f950213c343a7299821f7f924ed08fef2b554c31b06",
          "sha1": "32a28160eb26e79c82f64a6723f92ff14b1519c1",
          "md5": "c2bd3ee2233c901bc017afec94403397"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.1-common",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.2.jar",
          "url": "handbook-26.1.1-common-1.2.2.jar",
          "size": 622267,
          "sha512": "39989f119320886942051038402064e76576e2b4f27847e86612c2ff6a50d98ba8b50fd18a22e356c83230e871d7f8e9c671ea8c73736bc30d0c9a4466024279",
          "sha256": "d2b5a2de39864b86b97d0f950213c343a7299821f7f924ed08fef2b554c31b06",
          "sha1": "32a28160eb26e79c82f64a6723f92ff14b1519c1",
          "md5": "c2bd3ee2233c901bc017afec94403397"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.1-common-1.2.2-sources.jar",
          "url": "handbook-26.1.1-common-1.2.2-sources.jar",
          "size": 421354,
          "sha512": "a40721eb1a0f8bd4c402352e7f9902eecf405b4ebf8d8f8861355375b1f84db205f6cdee0657938cbcc6a64407165560fd1149a02fab61a778440aa0d4531db4",
          "sha256": "eee27b36343cf2dae2daa768bf81d2ff8f79a06e91b6f5b9e89b010ffa087d7b",
          "sha1": "6111c3da6046977dd8d0fa84fe03d21177ab09bf",
          "md5": "da63e3812f31299c8196c0235ffe13a8"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.2.2"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.1-common",
          "version": "1.2.2"
        }
      ]
    }
  ]
}
