{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.handbook",
    "module": "handbook-26.1.2-fabric",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "handbook-26.1.2-fabric-1.3.0.jar",
          "url": "handbook-26.1.2-fabric-1.3.0.jar",
          "size": 651400,
          "sha512": "670007c5c0d482a4298de90172c0bafd2eed0202507605287f49d2ac4802070ac9ad2f97b26ab782be515dddaa7a3ad5840f07aa6e4dacdb2f69da52c7b48afd",
          "sha256": "691088f8c2e059a519ccf34f33682eaad24475405bf05a958f9731fe00315f27",
          "sha1": "41cac42685b7ce39449ab5cb56d7af85313e8587",
          "md5": "50141a704cb12805cc11f9f3d9706f04"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.0"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.2-fabric",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.2-fabric",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "handbook-26.1.2-fabric-1.3.0.jar",
          "url": "handbook-26.1.2-fabric-1.3.0.jar",
          "size": 651400,
          "sha512": "670007c5c0d482a4298de90172c0bafd2eed0202507605287f49d2ac4802070ac9ad2f97b26ab782be515dddaa7a3ad5840f07aa6e4dacdb2f69da52c7b48afd",
          "sha256": "691088f8c2e059a519ccf34f33682eaad24475405bf05a958f9731fe00315f27",
          "sha1": "41cac42685b7ce39449ab5cb56d7af85313e8587",
          "md5": "50141a704cb12805cc11f9f3d9706f04"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.0"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.2-fabric",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "handbook-26.1.2-fabric-1.3.0-sources.jar",
          "url": "handbook-26.1.2-fabric-1.3.0-sources.jar",
          "size": 435755,
          "sha512": "4fdc91bc2b1cded623146f659731928ab4a58cb077ddc6d3bf002b261ba95c0ad8e01367292d35493774c87574c4c001394cca476401c8b0f55404ca56bdf9a8",
          "sha256": "2cb7798e099e54c68fabceaaceb1b3c95659f3be4fcde2bd382c361fc06046c7",
          "sha1": "bb2dbf8237e5166b59c7e74cc8f3fb94e0013e6a",
          "md5": "6b85cd0fccd7cdb4934f550b2230c7a9"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.handbook",
          "name": "handbook",
          "version": "1.3.0"
        },
        {
          "group": "technology.roughness.handbook",
          "name": "handbook-26.1.2-fabric",
          "version": "1.3.0"
        }
      ]
    }
  ]
}
