{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-common",
    "version": "1.0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.1.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.1.jar",
          "size": 132864,
          "sha512": "a32a294f94855ef9dfbb5ca6f22645f3a68ca79f840af3275a44ce0bb9f13f8baf7a336c8ca448be600daefe1d997013d222ae1470a03fb871bc7b296965e6f9",
          "sha256": "2c11db4bf89550cc1e4455136b32f70b6df22076fa0f476bb6bed0bc32cf5fd4",
          "sha1": "771072a11c868edfeeaf06bd2a9ade62ad281f32",
          "md5": "2c78d7acfde3deb8bc70bfa6d0303c19"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.1"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.1.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.1.jar",
          "size": 132864,
          "sha512": "a32a294f94855ef9dfbb5ca6f22645f3a68ca79f840af3275a44ce0bb9f13f8baf7a336c8ca448be600daefe1d997013d222ae1470a03fb871bc7b296965e6f9",
          "sha256": "2c11db4bf89550cc1e4455136b32f70b6df22076fa0f476bb6bed0bc32cf5fd4",
          "sha1": "771072a11c868edfeeaf06bd2a9ade62ad281f32",
          "md5": "2c78d7acfde3deb8bc70bfa6d0303c19"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.1"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.1"
        }
      ]
    }
  ]
}
