{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-common",
    "version": "1.0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.1.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.1.jar",
          "size": 132864,
          "sha512": "caee0f7c6817a3408a0579f7feef40a45da88415897d29e44840f4d87fbc67737f91c9376ddc2e4042819c93f31694e90bec8579d82f8bcb70191141546f39a7",
          "sha256": "2a5cd21c8f878525e19afbe360a0deec18b91ad2db466d68947cd578c6b0a2b2",
          "sha1": "d47ba8517e108d61031427d82e4ecae9b5803049",
          "md5": "cce0dfa6e862b52aaea81153af0dd070"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.1"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.0.0.1.jar",
          "url": "homeostaticseasons-1.21.1-common-1.0.0.1.jar",
          "size": 132864,
          "sha512": "caee0f7c6817a3408a0579f7feef40a45da88415897d29e44840f4d87fbc67737f91c9376ddc2e4042819c93f31694e90bec8579d82f8bcb70191141546f39a7",
          "sha256": "2a5cd21c8f878525e19afbe360a0deec18b91ad2db466d68947cd578c6b0a2b2",
          "sha1": "d47ba8517e108d61031427d82e4ecae9b5803049",
          "md5": "cce0dfa6e862b52aaea81153af0dd070"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.0.0.1"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.1"
        }
      ]
    }
  ]
}
