{
  "formatVersion": "1.1",
  "component": {
    "group": "guidebook",
    "module": "guidebook-1.21.1-fabric",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "guidebook-1.21.1-fabric-1.1.0.jar",
          "url": "guidebook-1.21.1-fabric-1.1.0.jar",
          "size": 652365,
          "sha512": "e97191a4a1cd9b7c03c2a58829a24805818be6d7f4343da4f0250fe2b74d28252d58b76c7e9083d6db2149a3ca250de9f1b43f645a389d158a1c897c868107ae",
          "sha256": "bb063e270d49b948ac2622adf12270dec4000d7f56cd78139a56ca4d3ff7510a",
          "sha1": "ebc6636617fb809145276660e5d2cfc65fd662c6",
          "md5": "cfe85b66c31cbe56788a17575b42ccca"
        }
      ],
      "capabilities": [
        {
          "group": "guidebook",
          "name": "guidebook-1.21.1-fabric",
          "version": "1.1.0"
        },
        {
          "group": "guidebook",
          "name": "guidebook",
          "version": "1.1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "13.0.8"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "15.0.140"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "16.0.799"
          }
        }
      ],
      "files": [
        {
          "name": "guidebook-1.21.1-fabric-1.1.0.jar",
          "url": "guidebook-1.21.1-fabric-1.1.0.jar",
          "size": 652365,
          "sha512": "e97191a4a1cd9b7c03c2a58829a24805818be6d7f4343da4f0250fe2b74d28252d58b76c7e9083d6db2149a3ca250de9f1b43f645a389d158a1c897c868107ae",
          "sha256": "bb063e270d49b948ac2622adf12270dec4000d7f56cd78139a56ca4d3ff7510a",
          "sha1": "ebc6636617fb809145276660e5d2cfc65fd662c6",
          "md5": "cfe85b66c31cbe56788a17575b42ccca"
        }
      ],
      "capabilities": [
        {
          "group": "guidebook",
          "name": "guidebook-1.21.1-fabric",
          "version": "1.1.0"
        },
        {
          "group": "guidebook",
          "name": "guidebook",
          "version": "1.1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guidebook-1.21.1-fabric-1.1.0-sources.jar",
          "url": "guidebook-1.21.1-fabric-1.1.0-sources.jar",
          "size": 442478,
          "sha512": "997426be9816e5642b67ab503e8fe8fe848cf0f0c1ca28c7bae7eb1fa9aedfa27ead36556036733e70fd2d097c52d08fdb7ec8372a4c7889cad7fcce20022ea2",
          "sha256": "de99b6895c9cd0d8fa2557b3f084546bc12393ff7572157c832abca7eede4bd5",
          "sha1": "5a6ebc019aa5cbcac189dde9890df3658993b1d3",
          "md5": "144ce6fff156d442baaee446377952aa"
        }
      ],
      "capabilities": [
        {
          "group": "guidebook",
          "name": "guidebook-1.21.1-fabric",
          "version": "1.1.0"
        },
        {
          "group": "guidebook",
          "name": "guidebook",
          "version": "1.1.0"
        }
      ]
    }
  ]
}
