{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-26.1.2-common",
    "version": "2.11.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-26.1.2-common-2.11.0.4.jar",
          "url": "homeostatic-26.1.2-common-2.11.0.4.jar",
          "size": 1563448,
          "sha512": "a48f366a3e48e4ab0ef9d8996ce85e6a8e196970b8a63357379258c73b4a425c982146ee1b1c6f915107963fac8d93242ad6d74e0e63c8866a60f4c17a99df14",
          "sha256": "8f80abad39d5dce0c23d7d366c559ad70f66081992eda0f0b5a76b324df24705",
          "sha1": "8e8638c3780f2eee07494ff456d1b62f7e239196",
          "md5": "1ff98c6a19e10fd6ca60dc93df9ce0ff"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.4"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-26.1.2-common",
          "version": "2.11.0.4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-26.1.2-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-26.1.2-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-26.1.2-common",
          "version": {
            "requires": "1.1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-26.1.2-common-2.11.0.4.jar",
          "url": "homeostatic-26.1.2-common-2.11.0.4.jar",
          "size": 1563448,
          "sha512": "a48f366a3e48e4ab0ef9d8996ce85e6a8e196970b8a63357379258c73b4a425c982146ee1b1c6f915107963fac8d93242ad6d74e0e63c8866a60f4c17a99df14",
          "sha256": "8f80abad39d5dce0c23d7d366c559ad70f66081992eda0f0b5a76b324df24705",
          "sha1": "8e8638c3780f2eee07494ff456d1b62f7e239196",
          "md5": "1ff98c6a19e10fd6ca60dc93df9ce0ff"
        }
      ]
    }
  ]
}
