{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-fabric",
    "version": "1.21.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.2.jar",
          "url": "whitenoise-fabric-1.21.8.2.jar",
          "size": 535727,
          "sha512": "6839a9fcd66ada8f2e52dbd8b3a3f027ee6498983b55fd7bab1c69e71e5e0b3e06a412e81d300b3128ac63afd3062f20b4d8eed4e12b884ea298a5f769a26e57",
          "sha256": "638a68921e18091af31138a0312e458ba3b9462277c25db44a9737820fdbeb3c",
          "sha1": "5333f85b68f5cf4a0d03ba5a32c559a375389a5c",
          "md5": "26c548e018d9d59cc200c139ef04b0e4"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.2"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.133.4+1.21.8"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.2.jar",
          "url": "whitenoise-fabric-1.21.8.2.jar",
          "size": 535727,
          "sha512": "6839a9fcd66ada8f2e52dbd8b3a3f027ee6498983b55fd7bab1c69e71e5e0b3e06a412e81d300b3128ac63afd3062f20b4d8eed4e12b884ea298a5f769a26e57",
          "sha256": "638a68921e18091af31138a0312e458ba3b9462277c25db44a9737820fdbeb3c",
          "sha1": "5333f85b68f5cf4a0d03ba5a32c559a375389a5c",
          "md5": "26c548e018d9d59cc200c139ef04b0e4"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.2"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-fabric-1.21.8.2-sources.jar",
          "url": "whitenoise-fabric-1.21.8.2-sources.jar",
          "size": 71649,
          "sha512": "3464f0032f319bdaac19dde082141be30413f431e2697b6255ab7ec9c71aba19e64880e8e597912fe138af0aa7bcdede5bbf366722f73a0ef50cb24550c5e6d5",
          "sha256": "cff223bc4d39ebb3883d8818c250713363cebd47d5e72582f17e2cf6b9787774",
          "sha1": "0141de1824586f331da164f0406377da9c9aa03e",
          "md5": "7b5611569c4c986af8684345b21f4a28"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-fabric",
          "version": "1.21.8.2"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.8.2"
        }
      ]
    }
  ]
}
