{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-1.21.1-common",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-1.21.1-common-2.0.5.jar",
          "url": "whitenoise-1.21.1-common-2.0.5.jar",
          "size": 160714,
          "sha512": "7b92441af5dbe4679e95882d26298d12acc90745ecae2c2126872311fe478701c2cdcb88f69d415c239b8ffe7d90172d351e2768d5e4b1c30bcbfafce89f51da",
          "sha256": "a27aa0bb6c29aafe5587597864b1dc39f2a228d6a742b8e2b8595d0dcfbfa425",
          "sha1": "41b15dd00cacc346a322c74152e6d5574bd90506",
          "md5": "7bd53b7adc71944d5766a15415c905c9"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.1-common",
          "version": "2.0.5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-1.21.1-common-2.0.5.jar",
          "url": "whitenoise-1.21.1-common-2.0.5.jar",
          "size": 160714,
          "sha512": "7b92441af5dbe4679e95882d26298d12acc90745ecae2c2126872311fe478701c2cdcb88f69d415c239b8ffe7d90172d351e2768d5e4b1c30bcbfafce89f51da",
          "sha256": "a27aa0bb6c29aafe5587597864b1dc39f2a228d6a742b8e2b8595d0dcfbfa425",
          "sha1": "41b15dd00cacc346a322c74152e6d5574bd90506",
          "md5": "7bd53b7adc71944d5766a15415c905c9"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.1-common",
          "version": "2.0.5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-1.21.1-common-2.0.5-sources.jar",
          "url": "whitenoise-1.21.1-common-2.0.5-sources.jar",
          "size": 85590,
          "sha512": "fd594d4dcc0a186bf16c45825a0b40958abde15ae2c5715ba7d4baebae7ae8d263edb3f6428b2ea7d37a1ddb89e4a18dafcd582b8058f6891a4966f92d7713be",
          "sha256": "4e6cb8c6607fdde84c7586d80968324f275c7eba876f35c4fdef338e74ced1b7",
          "sha1": "806f0a85c8c410c0533e8c1c60cb220de47e3efa",
          "md5": "5661489aec28ab6fe9c4b432d8f9333f"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.0.5"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.1-common",
          "version": "2.0.5"
        }
      ]
    }
  ]
}
