{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-common",
    "version": "1.21.1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.18.jar",
          "url": "whitenoise-common-1.21.1.18.jar",
          "size": 136425,
          "sha512": "02b3df2240a18518b5e27021b2dc460c54395b6a77563d1d25e2a56571517ec1e15db1adeb75fd467e715892b3fe05f81d509bb479c37018da0d87ebe9121659",
          "sha256": "fbee7d18e38f03662cb2537f820cb491612b228d57b22150b5339a72257d29ae",
          "sha1": "ccac8f09dfe197e635044738e974a13c0924e8bb",
          "md5": "ac3e8883829342dc6087d39191a12ada"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.18"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-common-1.21.1.18.jar",
          "url": "whitenoise-common-1.21.1.18.jar",
          "size": 136425,
          "sha512": "02b3df2240a18518b5e27021b2dc460c54395b6a77563d1d25e2a56571517ec1e15db1adeb75fd467e715892b3fe05f81d509bb479c37018da0d87ebe9121659",
          "sha256": "fbee7d18e38f03662cb2537f820cb491612b228d57b22150b5339a72257d29ae",
          "sha1": "ccac8f09dfe197e635044738e974a13c0924e8bb",
          "md5": "ac3e8883829342dc6087d39191a12ada"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.18"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-common-1.21.1.18-sources.jar",
          "url": "whitenoise-common-1.21.1.18-sources.jar",
          "size": 57632,
          "sha512": "8119d23d2c0ce1e29197299eec14aee2bcb7001c17e948d57156343ab83603b9617083db5dbcd8a1dcf58b02cce71ed55be2ba9b5a09df92900dcbdd0b6b30a3",
          "sha256": "44167d968e666173758bd35f27d0009ab1403fe340e1899ccea2dcf03ceea8d7",
          "sha1": "b639400374e29bcebef342d837a558d7a7fabded",
          "md5": "4720cb9ace890d8aecaa47fa3cecc756"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-common",
          "version": "1.21.1.18"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "1.21.1.18"
        }
      ]
    }
  ]
}
