{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-common",
    "version": "1.1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.1.0.0.jar",
          "url": "homeostaticseasons-1.21.1-common-1.1.0.0.jar",
          "size": 135497,
          "sha512": "aa95249134a87fc2c3f80441c1ed4230282af0c3bf93ddae634c434c32c0e3f534b422e6277fa3882f3bb1bf287a86d27cd535489818eb987d9724cb8d7fb346",
          "sha256": "a423dadca24c84f5c3b93199654d90cec44afac49f8057b3fd45feb33cec1ce2",
          "sha1": "c7acdee053d41fb5b5603ff2d088141f36ae3a06",
          "md5": "a937f92c4dbe89e271d44a1b29505039"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.1.0.0"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.1.0.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-common",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-common-1.1.0.0.jar",
          "url": "homeostaticseasons-1.21.1-common-1.1.0.0.jar",
          "size": 135497,
          "sha512": "aa95249134a87fc2c3f80441c1ed4230282af0c3bf93ddae634c434c32c0e3f534b422e6277fa3882f3bb1bf287a86d27cd535489818eb987d9724cb8d7fb346",
          "sha256": "a423dadca24c84f5c3b93199654d90cec44afac49f8057b3fd45feb33cec1ce2",
          "sha1": "c7acdee053d41fb5b5603ff2d088141f36ae3a06",
          "md5": "a937f92c4dbe89e271d44a1b29505039"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.1.0.0"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-common",
          "version": "1.1.0.0"
        }
      ]
    }
  ]
}
