{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.whitenoise",
    "module": "whitenoise-1.21.1-fabric",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "whitenoise-1.21.1-fabric-2.2.0.jar",
          "url": "whitenoise-1.21.1-fabric-2.2.0.jar",
          "size": 564599,
          "sha512": "d6b3c004f926b47f5d9f2b209803db7ac9ee8b283fa1d4195c631261d08fcc4ffa15fefdc5a63e072c01730ac099542fc931b936da92f1cffec6688e5b7f1583",
          "sha256": "ff1bbcbebd5047c5a5adc5b67b0ede7ebdf25050c16424faf1863c2ae6a822ad",
          "sha1": "d9c71c8eee30aa84239c07e778cfac1c85e6314d",
          "md5": "e41551aaf81b4f346f265f3f466f4b34"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.2.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.1-fabric",
          "version": "2.2.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "whitenoise-1.21.1-fabric-2.2.0.jar",
          "url": "whitenoise-1.21.1-fabric-2.2.0.jar",
          "size": 564599,
          "sha512": "d6b3c004f926b47f5d9f2b209803db7ac9ee8b283fa1d4195c631261d08fcc4ffa15fefdc5a63e072c01730ac099542fc931b936da92f1cffec6688e5b7f1583",
          "sha256": "ff1bbcbebd5047c5a5adc5b67b0ede7ebdf25050c16424faf1863c2ae6a822ad",
          "sha1": "d9c71c8eee30aa84239c07e778cfac1c85e6314d",
          "md5": "e41551aaf81b4f346f265f3f466f4b34"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.2.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.1-fabric",
          "version": "2.2.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whitenoise-1.21.1-fabric-2.2.0-sources.jar",
          "url": "whitenoise-1.21.1-fabric-2.2.0-sources.jar",
          "size": 101609,
          "sha512": "16d13fa239fd955140807801f075aa0d325184a34566aa5bf7dc08fc313005f840904d9bf8d9e0b49279d5c218396a3a81a33b3ee4028b89e690ec175348858e",
          "sha256": "e6f7aecd6b6c78e373eb35790d98b18bf82eeba76b8915444639a3890f4dcbc1",
          "sha1": "5a69b33d929479d96a5cc6c4ebd8d1ebd29be7df",
          "md5": "261480b9d5d8d651b9b4c580143ae6fe"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise",
          "version": "2.2.0"
        },
        {
          "group": "technology.roughness.whitenoise",
          "name": "whitenoise-1.21.1-fabric",
          "version": "2.2.0"
        }
      ]
    }
  ]
}
