{
  "formatVersion": "1.1",
  "component": {
    "group": "technology.roughness.guidebook",
    "module": "guidebook-1.21.1-common",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "guidebook-1.21.1-common-1.1.1.jar",
          "url": "guidebook-1.21.1-common-1.1.1.jar",
          "size": 617099,
          "sha512": "eb8700092fc703ba9aa52cee31ccb0715e6bbd18c18f94865564b4da3e29da8f8a59af3dfd6393fd0cbb4101fa3383d94f9483c0190a2ecb9fc501633674fcb1",
          "sha256": "1b6514a4434480981df83aba5cd21e8fca877bd98f12e48ad3655f80e628cfdf",
          "sha1": "489c038b9c083ff56dda2aa6d8913ce12082a9f5",
          "md5": "5df7a7776001908f6433ba67f5d10472"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook",
          "version": "1.1.1"
        },
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook-1.21.1-common",
          "version": "1.1.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-common",
          "version": {
            "requires": "2.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "guidebook-1.21.1-common-1.1.1.jar",
          "url": "guidebook-1.21.1-common-1.1.1.jar",
          "size": 617099,
          "sha512": "eb8700092fc703ba9aa52cee31ccb0715e6bbd18c18f94865564b4da3e29da8f8a59af3dfd6393fd0cbb4101fa3383d94f9483c0190a2ecb9fc501633674fcb1",
          "sha256": "1b6514a4434480981df83aba5cd21e8fca877bd98f12e48ad3655f80e628cfdf",
          "sha1": "489c038b9c083ff56dda2aa6d8913ce12082a9f5",
          "md5": "5df7a7776001908f6433ba67f5d10472"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook",
          "version": "1.1.1"
        },
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook-1.21.1-common",
          "version": "1.1.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "guidebook-1.21.1-common-1.1.1-sources.jar",
          "url": "guidebook-1.21.1-common-1.1.1-sources.jar",
          "size": 418182,
          "sha512": "3c8b55ad18271117697140864e5c19bbde6353ea7ece4c3147964a96c640a4aa45334060351caad80f8ec2f39fd8eb51a4daa6ea97862d146f3c45e8a182f1f6",
          "sha256": "13c8fb230e4341821c911306b7a664eb6f7c50db198b7b2f4d21bfec387b2644",
          "sha1": "e70bebec176cd28d12ab5e02801db44ea3f10f13",
          "md5": "6b82ae5568815ba32314b99f14919048"
        }
      ],
      "capabilities": [
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook",
          "version": "1.1.1"
        },
        {
          "group": "technology.roughness.guidebook",
          "name": "guidebook-1.21.1-common",
          "version": "1.1.1"
        }
      ]
    }
  ]
}
