{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostatic",
    "module": "homeostatic-1.21.1-fabric",
    "version": "2.11.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.1.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.1.jar",
          "size": 2739557,
          "sha512": "5f976247190b8ee9920a6c6e5e8db2056315ff1c9075eecb8395945cd91be0c0884941a855c838616fcce2962a53ee3b8c85b851cd82a924147d2643570cde78",
          "sha256": "08b77b55b3034fa6dc56a74c8cd78085d063a58998d79eeb989e03ff164f2b8f",
          "sha1": "98fa23f143c49ed21bf0a8e16055d261d1fd51bf",
          "md5": "22589f039cf2cc957093b788b8526f9e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.11.0.1"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "technology.roughness.handbook",
          "module": "handbook-1.21.1-fabric",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "module": "homeostaticseasons-1.21.1-fabric",
          "version": {
            "requires": "1.0.0.3"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-base",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "org.ladysnake.cardinal-components-api",
          "module": "cardinal-components-entity",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostatic-1.21.1-fabric-2.11.0.1.jar",
          "url": "homeostatic-1.21.1-fabric-2.11.0.1.jar",
          "size": 2739557,
          "sha512": "5f976247190b8ee9920a6c6e5e8db2056315ff1c9075eecb8395945cd91be0c0884941a855c838616fcce2962a53ee3b8c85b851cd82a924147d2643570cde78",
          "sha256": "08b77b55b3034fa6dc56a74c8cd78085d063a58998d79eeb989e03ff164f2b8f",
          "sha1": "98fa23f143c49ed21bf0a8e16055d261d1fd51bf",
          "md5": "22589f039cf2cc957093b788b8526f9e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic-1.21.1-fabric",
          "version": "2.11.0.1"
        },
        {
          "group": "com.github.wendall911.homeostatic",
          "name": "homeostatic",
          "version": "2.11.0.1"
        }
      ]
    }
  ]
}
