{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-fabric",
    "version": "1.0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.2.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.2.jar",
          "size": 762659,
          "sha512": "248ac4dddf3aa7d3cce7486f93de2395c839e43ad1a14339e19fea19e8105e5e36bcc978b9ca9092362c636e26f3d13f77edb98c1f829178bf7d691497c4e606",
          "sha256": "1b773b119757cbe5554a65853107a96fa66b54a4a5edd6adabeeedcaae3856a9",
          "sha1": "7f055eefb2b591426d5ffcf76c1db9cb5dde155e",
          "md5": "fbf47cbca66f825fe69bea389798df14"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.2"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.2.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.2.jar",
          "size": 762659,
          "sha512": "248ac4dddf3aa7d3cce7486f93de2395c839e43ad1a14339e19fea19e8105e5e36bcc978b9ca9092362c636e26f3d13f77edb98c1f829178bf7d691497c4e606",
          "sha256": "1b773b119757cbe5554a65853107a96fa66b54a4a5edd6adabeeedcaae3856a9",
          "sha1": "7f055eefb2b591426d5ffcf76c1db9cb5dde155e",
          "md5": "fbf47cbca66f825fe69bea389798df14"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.2"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.2"
        }
      ]
    }
  ]
}
