{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.wendall911.homeostaticseasons",
    "module": "homeostaticseasons-1.21.1-fabric",
    "version": "1.0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.2.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.2.jar",
          "size": 762660,
          "sha512": "bd3a4fd29178f1e6c4b70c66e9c3c5dd68d15f92c93d21d0c478eb9676978de61b3252ebccecb857b69906eea0a7fdfe78ea4ce2b915b053533330b824dc7d69",
          "sha256": "95a6afbf5e05dcb41d4b92cd0304e50e232a2177055cd4e66f0ce7f33af7ce23",
          "sha1": "eee6ef00f1740c81820b7b885333ac905a293618",
          "md5": "3171d5a2c980b6fc8ce928fd5f4dbd4e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.2"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.6+1.21.1"
          }
        },
        {
          "group": "com.github.wendall911.climatesettings",
          "module": "climatesettings-1.21.1-fabric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "technology.roughness.whitenoise",
          "module": "whitenoise-1.21.1-fabric",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.7"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "glitchcore-955399",
          "version": {
            "requires": "5660741"
          }
        },
        {
          "group": "curse.maven",
          "module": "terrablender-565956",
          "version": {
            "requires": "5864141"
          }
        },
        {
          "group": "curse.maven",
          "module": "byg-1070751",
          "version": {
            "requires": "5894945"
          }
        },
        {
          "group": "curse.maven",
          "module": "tyg-962544",
          "version": {
            "requires": "5691179"
          }
        },
        {
          "group": "curse.maven",
          "module": "corgilib-693313",
          "version": {
            "requires": "5691272"
          }
        },
        {
          "group": "software.bernie.geckolib",
          "module": "geckolib-fabric-1.21.1",
          "version": {
            "requires": "4.7"
          }
        }
      ],
      "files": [
        {
          "name": "homeostaticseasons-1.21.1-fabric-1.0.0.2.jar",
          "url": "homeostaticseasons-1.21.1-fabric-1.0.0.2.jar",
          "size": 762660,
          "sha512": "bd3a4fd29178f1e6c4b70c66e9c3c5dd68d15f92c93d21d0c478eb9676978de61b3252ebccecb857b69906eea0a7fdfe78ea4ce2b915b053533330b824dc7d69",
          "sha256": "95a6afbf5e05dcb41d4b92cd0304e50e232a2177055cd4e66f0ce7f33af7ce23",
          "sha1": "eee6ef00f1740c81820b7b885333ac905a293618",
          "md5": "3171d5a2c980b6fc8ce928fd5f4dbd4e"
        }
      ],
      "capabilities": [
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons",
          "version": "1.0.0.2"
        },
        {
          "group": "com.github.wendall911.homeostaticseasons",
          "name": "homeostaticseasons-1.21.1-fabric",
          "version": "1.0.0.2"
        }
      ]
    }
  ]
}
